project:
  type: website
  output-dir: docs
  render:
  - index.qmd
  - about.qmd
  - resumes.qmd
  - slides_2021.qmd
  - slides_2022.qmd
  - slides/2022/first/first.qmd
  - resumes/classic/index.qmd
  - resumes/spotify/index.qmd

format:
  html:
    theme:
      dark: [darkly, css/styles-dark.scss]
      light: [litera, css/styles.scss]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    df-print: kable
    smooth-scroll: true
    link-external-newwindow: true
    linkcolor: '#BC0031'
    
website:
  # favicon: 
  title: "Joschka Schwarz"
  site-url: https://jwarz.github.io
  repo-url: https://github.com/jwarz/jwarz.github.io
  repo-actions: [edit, issue]
  #  google-analytics: "UA-107432294-1"
  sidebar:
    style: "docked"
    contents:
      - section: "Presentations"
        contents:
          - slides_2022.qmd
          - slides_2021.qmd
      - text: "Resumes"
        href: resumes.qmd
  page-navigation: true
  search: false
  navbar:
    #background: '#00C1D4'
    pinned: true
    right:
      - text: About
        href: about.qmd
      - icon: github
        href: https://github.com/jwarz/
        aria-label: Quarto GitHub
      - icon: linkedin
        href: https://linkedin.com/j-schwarz/
        aria-label: Quarto LinkedIn
  page-footer:
    right: "This blog is built with ❤️ and [Quarto](https://quarto.org/)."
    left: |
      Proudly supported by
      [![](https://www.rstudio.com/wp-content/uploads/2018/10/RStudio-Logo-flat.svg){fig-alt="RStudio" width=65px}](https://www.rstudio.com)

        
# 
# freeze: false