project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    # - "!revealjs/slides/"

execute:
  freeze: auto  # Re-render only when source changes

website:
  # favicon: 
  title: "Joschka Schwarz"
  site-url: https://jwarz.github.io
  repo-url: https://github.com/jwarz/jwarz.github.io
  repo-actions: [edit, issue]
  #  google-analytics: "UA-*********-*"
  page-navigation: true
  reader-mode: true
  search: true
  navbar:
    pinned: true
    # background: "#EE6A24"
    right:
      - text: About
        href: index.qmd
      - icon: github
        href: https://github.com/jwarz/
        aria-label: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/j-schwarz
        aria-label: Quarto LinkedIn
    left:
      - text: "Tutorials"
        menu:
          - text: "R"
            file: content/R/index.qmd
          - text: "Python"
            file: content/python/index.qmd
      - text: "Presentations"
        file: slides/index.qmd
      - text: "Resumes"
        file: resumes/index.qmd

  sidebar:
    - title: "R"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Overview"
          file: content/R/index.qmd
        - text: "---"    
        - section: "R Manuals"
          contents:
            - text: "1: An Introduction to R"
              file: content/R/r-manuals/test.qmd
            - text: "2: R Data Import/Export"
              file: content/R/r-manuals/02-content.qmd
            - text: "3: R Installation and Administration"
              file: content/R/r-manuals/03-content.qmd
            - text: "4: Writing R Extensions"
              file: content/R/r-manuals/04-content.qmd
            - text: "5: R Language Definition"
              file: content/R/r-manuals/05-content.qmd
            - text: "6: R Internals"
              file: content/R/r-manuals/06-content.qmd
        - text: "---"
        - section: "DataCamp"
          contents:
            - text: "1: Evaluation and the causal revolution"
              file: content/R/r-manuals/01-content.qmd
            - text: "2: Regression and inference"
              file: content/R/r-manuals/02-content.qmd
            - text: "3: Theories of change and logic models"
              file: content/R/r-manuals/03-content.qmd

    - title: "Python"
      contents:
        - text: "Overview"
          file: content/python/index.qmd
        - text: "---"
        - section: "Other projects"
          contents:
            - content/python/final-project.qmd
            - content/python/weekly-check-in.qmd
        - section: "Problem sets"
          contents:
            - content/python/01-problem-set.qmd
            - content/python/02-problem-set.qmd
            - content/python/03-problem-set.qmd
        - section: "Evaluation"
          contents:
            - content/python/01-eval-background-theory.qmd
            - content/python/02-eval-measurement.qmd
            - content/python/03-eval-dag.qmd
            
    - title: "Presentations"
      contents:
          - text: "Overview"
            file: slides/index.qmd
          - text: "---"
          - section: "2021"
            contents:
              - text: "Pres 1"
                file: slides/random-numbers.qmd
              - text: "Pres 2"
                file: slides/synthetic-data.qmd
          - text: "---"
          - section: "2022"
            contents:
              - text: "Pres 3"
                file: slides/slides_2021.qmd
              - text: "Pres 4"
                file: slides/slides_2022.qmd
        
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var website.copyright_year >}} by [{{< var instructor.name >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var website.github >}})

format:
  html:
    theme:
      dark: [darkly, css/styles-dark.scss]
      light: [litera, css/styles.scss]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    df-print: kable
    smooth-scroll: true
    link-external-newwindow: false
    linkcolor: '#BC0031'