project:
  type: website
  #output-dir: docs
  render:
    - "*.qmd"
execute: 
  freeze: auto  # Re-render only when source changes

website:
  # favicon: 
  title: "Joschka Schwarz"
  site-url: https://jwarz.github.io
  repo-url: https://github.com/jwarz/jwarz.github.io
  repo-actions: [edit, issue]
  #  google-analytics: "UA-*********-*"
  page-navigation: true
  reader-mode: true
  search: true
  navbar:
    pinned: true
    # background: "#EE6A24"
    right:
      - text: About
        href: index.qmd
      - icon: github
        href: https://github.com/jwarz/
        aria-label: Quarto GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/j-schwarz
        aria-label: Quarto LinkedIn
    left:
      - text: "Data Science"
        menu:
          - text: "R"
            file: content/R/index.qmd
          - text: "Python"
            file: content/python/index.qmd
          - text: "SQL"
            file: content/sql/index.qmd
      - text: "Presentations"
        file: slides/index.qmd
      - text: "Resumes"
        file: resumes/index.qmd

  sidebar:
    - title: "R"
      style: "docked"
      search: false
      background: dark
      contents:
        - text: "Overview"
          file: content/R/index.qmd
        - text: "---"
        - section: "Topics"
          contents:
            - text: "<b><i>1 Programming Basics</i></b>"
            - text: "---"
            - text: "1.1: Introduction to R"
              file: content/R/topics/01_basics/01_programming_beginner/01_programming_beginner.qmd
            - text: "1.2: Intermediate R"
              file: content/R/topics/01_basics/02_programming_intermediate/02_programming_intermediate.qmd
            - text: "1.3: Introduction to the tidyverse"
              file: content/R/topics/01_basics/03_programming_tidyverse/03_programming_tidyverse.qmd
            - text: "---"
            - text: "<b><i>2 Importing Data</i></b>"
            - text: "---"
            - text: "2.1: Introduction to Importing Data"
              file: content/R/topics/02_importing_data/01_importing_data_beginner/01_importing_data_beginner.qmd
            - text: "2.2: Intermediate Importing Data"
              file: content/R/topics/02_importing_data/02_importing_data_intermediate/02_importing_data_intermediate.qmd
            - text: "2.3: Working with web data"
              file: content/R/topics/02_importing_data/03_working_with_web_data/03_working_with_web_data.qmd
            - text: "---"
            - text: "<b><i>3 Data Wrangling</i></b>"
            - text: "---"
            - text: "3.1: Data Manipulation with dplyr"
              file: content/R/topics/03_data_wrangling/01_data_manipulation_with_dplyr/01_data_manipulation_with_dplyr.qmd
            - text: "3.2: Joining data with dplyr"
              file: content/R/topics/03_data_wrangling/02_joining_data_with_dplyr/02_joining_data_with_dplyr.qmd
            - text: "3.3: Exploratory Data Analysis"
              file: content/R/topics/03_data_wrangling/exploratory_data_analysis_in_r/exploratory_data_analysis_in_r.qmd
            - text: "3.4: Case Study: EDA"
              file: content/R/topics/03_data_wrangling/case_study_exploratory_data_analysis_in_r/case_study_exploratory_data_analysis_in_r.qmd
            - text: "3.5: Cleaning Data"
              file: content/R/topics/03_data_wrangling/cleaning_data_in_r/cleaning_data_in_r.qmd
            - text: "3.6: Data Manipulation with data.table"
              file: content/R/topics/03_data_wrangling/data_manipulation_with_datatable/data_manipulation_with_datatable.qmd
            - text: "3.7: Joining Data with data.table"
              file: content/R/topics/03_data_wrangling/joining_data_with_datatable/joining_data_with_datatable.qmd
            - text: "---"
            - text: "<b><i>4 Data Visualization</i></b>"
            - text: "---"
            - text: "4.1: Introduction to Data Visualization with ggplot2"
              file: content/R/topics/04_data_visualization/introduction_to_data_visualization_with_ggplot2/ggplot2_intro.qmd
            - text: "4.2: Intermediate Data Visualization with ggplot2"
              file: content/R/topics/04_data_visualization/data_visualization_with_ggplot2_intermediate/ggplot2_intermediate.qmd
            - text: "---"
            - text: "<b><i>5 Statistics</i></b>"
            - text: "---"
            - text: "5.1: Introduction to Statistics"
              file: content/R/topics/05_statistics/01_statistics_beginner/01_statistics_beginner.qmd
            - text: "5.2: Foundations of Probability"
              file: content/R/topics/05_statistics/02_foundations_of_probability_in_r/02_foundations_of_probability_in_r.qmd
            - text: "5.3: Introduction to Regression"
              file: content/R/topics/05_statistics/03_regression_beginner/03_regression_beginner.qmd
            - text: "5.4: Intermediate Regression"
              file: content/R/topics/05_statistics/04_regression_intermediate/04_regression_intermediate.qmd
            - text: "5.5: Modeling with Data in the Tidyverse"
              file: content/R/topics/05_statistics/06_modeling_with_data_in_the_tidyverse/06_modeling_with_data_in_the_tidyverse.qmd
            - text: "5.6: Experimental Design"
              file: content/R/topics/05_statistics/09_experimental_design/09_experimental_design.qmd
            - text: "5.7: A/B Testing"
              file: content/R/topics/05_statistics/10_ab_testing_in_r/10_ab_testing_in_r.qmd
            - text: "5.8: Fundamentals of Bayesian Data Analysis"
              file: content/R/topics/05_statistics/19_fundamentals_of_bayesian_data_analysis/19_fundamentals_of_bayesian_data_analysis.qmd
            - text: "5.9: Factor Analysis"
              file: content/R/topics/05_statistics/21_factor_analysis_in_r/21_factor_analysis_in_r.qmd
            - text: "---"
            - text: "<b><i>7 Machine Learning</i></b>"
            - text: "---"
            - text: "7.1: Supervised Learning: Classification"
              file: content/R/topics/07_machine_learning/01_supervised_learning_classification/01_supervised_learning_classification.qmd
            - text: "7.2: Supervised Learning: Regression"
              file: content/R/topics/07_machine_learning/02_supervised_learning_regression/02_supervised_learning_regression.qmd
            - text: "7.3: Unsupervised Learning"
              file: content/R/topics/07_machine_learning/03_unsupervised_learning/03_unsupervised_learning.qmd
            - text: "7.4: Machine Learning in the tidyverse"
              file: content/R/topics/07_machine_learning/04_machine_learning_in_the_tidyverse/04_machine_learning_in_the_tidyverse.qmd
            - text: "7.5: Cluster Analysis"
              file: content/R/topics/07_machine_learning/05_cluster_analysis/05_cluster_analysis.qmd
            - text: "7.6: Machine Learning with caret"
              file: content/R/topics/07_machine_learning/06_machine_learning_with_caret/06_machine_learning_with_caret.qmd
            - text: "7.7: Modeling with tidymodels"
              file: content/R/topics/07_machine_learning/07_modeling_with_tidymodels/07_modeling_with_tidymodels.qmd
            - text: "7.8: Machine Learning with tree-based Models"
              file: content/R/topics/07_machine_learning/08_machine_learning_with_tree-based_models/08_machine_learning_with_tree-based_models.qmd
            - text: "7.9: Support Vector Machines"
              file: content/R/topics/07_machine_learning/09_support_vector_machines/09_support_vector_machines.qmd
            - text: "7.10: Topic Modeling"
              file: content/R/topics/07_machine_learning/10_topic_modeling/10_topic_modeling.qmd
            - text: "7.11: Hyperparameter Tuning"
              file: content/R/topics/07_machine_learning/11_hyperparameter_tuning/11_hyperparameter_tuning.qmd
            - text: "7.12: Bayesian Regression Modeling"
              file: content/R/topics/07_machine_learning/12_bayesian_regression_modeling_with_rstanarm/12_bayesian_regression_modeling_with_rstanarm.qmd
            - text: "7.13: Introduction to Spark"
              file: content/R/topics/07_machine_learning/13_spark_with_sparklyr_in_R/13_spark_with_sparklyr_in_R.qmd
        - text: "---"    
        - section: "R Manuals"
          contents:
            - text: "1: An Introduction to R"
              file: content/R/r-manuals/test.qmd
            - text: "2: R Data Import/Export"
              file: content/R/r-manuals/02-content.qmd
            - text: "3: R Installation and Administration"
              file: content/R/r-manuals/03-content.qmd
            - text: "4: Writing R Extensions"
              file: content/R/r-manuals/04-content.qmd
            - text: "5: R Language Definition"
              file: content/R/r-manuals/05-content.qmd
            - text: "6: R Internals"
              file: content/R/r-manuals/06-content.qmd

    - title: "Python"
      contents:
        - text: "Overview"
          file: content/python/index.qmd
        - text: "---"
        - section: "Other projects"
          contents:
            - content/python/final-project.qmd
            - content/python/weekly-check-in.qmd
        - section: "Problem sets"
          contents:
            - content/python/01-problem-set.qmd
            - content/python/02-problem-set.qmd
            - content/python/03-problem-set.qmd
        - section: "Evaluation"
          contents:
            - content/python/01-eval-background-theory.qmd
            - content/python/02-eval-measurement.qmd
            - content/python/03-eval-dag.qmd
            
    - title: "SQL"
      contents:
        - text: "Overview"
          file: content/sql/index.qmd
        - text: "---"
        - section: "SQL"
          contents:
            - content/sql/introduction_to_relational_databases_in_sql/introduction_to_relational_databases_in_sql.qmd
            - content/sql/introduction_to_sql/introduction_to_sql.qmd
            - content/sql/joining_data_in_sql/joining_data_in_sql.qmd

    - title: "Presentations"
      contents:
          - text: "Overview"
            file: slides/index.qmd
          - text: "---"
          - section: "2023"
            contents:
              - text: "Diss"
                file: slides/slides_2023.qmd
          - text: "---"
          - section: "2022"
            contents:
              - text: "January"
                file: slides/slides_2021.qmd
              - text: "February"
                file: slides/slides_2022.qmd
          - text: "---"
          - section: "2021"
            contents:
              - text: "Pres 1"
                file: slides/random-numbers.qmd
              - text: "Pres 2"
                file: slides/synthetic-data.qmd

        
  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var website.copyright_year >}} by [{{< var instructor.name >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var website.github >}})

format:
  html:
    theme:
      dark: [darkly, css/styles-dark.scss]
      light: [litera, css/styles.scss]
    highlight-style: a11y-dark
    mainfont: "Atkinson Hyperlegible"
    code-block-background: true
    code-block-border-left: true
    code-copy: true
    code-overflow: scroll
    code-line-numbers: true
    code-link: true
    code-summary: "Show the code"
    execute: 
      eval: true
      echo: true
    df-print: paged
    smooth-scroll: true
    link-external-newwindow: false
    linkcolor: '#BC0031'
    number-sections: true
    number-depth: 2
    toc: true
    toc-depth: 2
    toc-title: Contents
knitr:
  opts_chunk: 
    comment: "#>" 
filters:
   - lightbox
lightbox: auto