{
  "hash": "71cb1bfab6a4740294fc6c52742a694e",
  "result": {
    "markdown": "---\ntitle: \"Introduction to Statistics in R\"\nauthor: \"Joschka Schwarz\"\n---\n\n\n\n\nStatistics is the study of how to collect, analyze, and draw conclusions from data. It’s a hugely valuable tool that you can use to bring the future into focus and infer the answer to tons of questions. For example, what is the likelihood of someone purchasing your product, how many calls will your support team receive, and how many jeans sizes should you manufacture to fit 95% of the population? In this course, you'll use sales data to discover how to answer questions like these as you grow your statistical skills and learn how to calculate averages, use scatterplots to show the relationship between numeric values, and calculate correlation. You'll also tackle probability, the backbone of statistical reasoning, and learn how to conduct a well-designed study to draw your own conclusions from data.\n\n# 1. Summary Statistics\n\nSummary statistics gives you the tools you need to boil down massive datasets to reveal the highlights. In this chapter, you'll explore summary statistics including mean, median, and standard deviation, and learn how to accurately interpret them. You'll also develop your critical thinking skills, allowing you to choose the best summary statistics for your data.\n\n## What is statistics?\n\nTheory. Coming soon ...\n\n\n**1. What is statistics?**\n\nHi and welcome to the course. My name is Maggie, and I'll be your host as we dive in to the world of statistics.\n\n**2. What is statistics?**\n\nSo what is statistics anyway? We can talk about the field of statistics, which is the practice and study of collecting and analyzing data. We can also talk about a summary statistic, which is a fact about or summary of some data, like an average or a count.\n\n**3. What can statistics do?**\n\nA more important question, however, is what can statistics do? With the power of statistics, we can answer tons of different questions like:How likely is someone to purchase a product? Are people more likely to purchase it if they can use a different payment system?How many occupants will your hotel have? How can you optimize occupancy?How many sizes of jeans need to be manufactured so they can fit 95% of the population? Should the same number of each size be produced?A question like, Which ad is more effective in getting people to purchase a product? can be answered with A/B testing.\n\n**4. What can't statistics do?**\n\nWhile statistics can answer a lot of questions, it's important to note that statistics can't answer every question. If we want to know why the TV series Game of Thrones is so popular, we could ask everyone why they like it, but they may lie or leave out reasons. We can see if series with more violent scenes attract more viewers, but even if they do, we can't know if the violence in Game of Thrones is the reason for its popularity, or if other factors are driving its popularity and it just happens to be violent.\n\n**5. Types of statistics**\n\nThere are 2 main branches of statistics: descriptive statistics and inferential statistics. Descriptive statistics focuses on describing and summarizing the data at hand. After asking four friends how they get to work, we can see that 50% of them drive to work, 25% ride the bus, and 25% bike. These are examples of descriptive statistics.Inferential statistics uses the data at hand, which is called sample data, to make inferences about a larger population. We could use inferential statistics to figure out what percent of people drive to work based on our sample data.\n\n**6. Types of data**\n\nThere are two main types of data. Numeric, or quantitative data is made up of numeric values. Categorical, or qualitative data is made up of values that belong to distinct groups.It's important to note that these aren't the only two types of data that exist - there are others too, but we'll be focusing on these two.Numeric data can be further separated into continuous and discrete data. Continuous numeric data is often quantities that can be measured, like speed or time. Discrete numeric data is usually count data, like number of pets or number of packages shipped.Categorical data can be nominal or ordinal. Nominal categorical data is made up of categories with no inherent ordering, like marriage status or country of residence. Ordinal categorical data has an inherent order, like a survey question where you need to indicate the degree to which you agree with a statement.\n\n**7. Categorical data can be represented as numbers**\n\nSometimes, categorical variables are represented using numbers. Married and unmarried can be represented using 1 and 0, or an agreement scale could be represented with numbers 1 through 5. However, it's important to note that this doesn't necessarily make them numeric variables.\n\n**8. Why does data type matter?**\n\nBeing able to identify data types is important since the type of data you're working with will dictate what kinds of summary statistics and visualizations make sense for your data, so this is an important skill to master.For numerical data, we can use summary statistics like mean, and plots like scatterplots, but these don't make a ton of sense for categorical data.\n\n**9. Why does data type matter?**\n\nSimilarly, things like counts and barplots don't make much sense for numeric data.\n\n**10. Let's practice!**\n\nTime to master these important skills!\n\n## Descriptive and inferential statistics\n\nStatistics can be used to answer lots of different types of questions, but being able to identify which type of statistics is needed is essential to drawing accurate conclusions. In this exercise, you'll sharpen your skills by identifying which type is needed to answer each question.\n\nIdentify which questions can be answered with descriptive statistics and which questions can be answered with inferential statistics.\n\n| Descriptive | Inferential |\n| --- | --- |\n| Given data on all 100,000 people who viewed an ad, what percent of people clicked on it? | Given data on 20 fish caught in a lake, what's the average weight of all fish in the lake? |\n| Given data on every customer service request made, what's the average time it took to respond? | After interviewing 100 customers, what percent of *all* your customers are satisfied with your product? |\n\n## Data type classification\n\nIn the video, you learned about two main types of data: numeric and categorical. Numeric variables can be classified as either discrete or continuous, and categorical variables can be classified as either nominal or ordinal. These characteristics of a variable determine which ways of summarizing your data will work best.\n\nMap each variable to its data type by dragging and dropping.\n\n| Continuous numeric | Discrete numeric | Categorical |\n| --- | --- | --- |\n| Kilowatts of electricity used | Number of items in stock | Brand of a product |\n| Air temperature | Number of DataCamp courses taken | Postal Code |\n| | Number of clicks on an ad | |\n\n## Measures of center\n\nTheory. Coming soon ...\n\n\n**1. Measures of center**\n\nIn this lesson, we'll begin to discuss summary statistics, some of which you may already be familiar with, like mean and median.\n\n**2. Mammal sleep data**\n\nIn this video, we'll look at data about different mammals' sleep habits.\n\n**3. Histograms**\n\nBefore we dive in, let's remind ourselves how histograms work. A histogram takes a bunch of data points and separates them into bins, or ranges of values. Here, there's a bin for 0 to 2 hours, 2 to 4 hours, and so on. The heights of the bars represent the number of data points that fall into that bin, so there's one mammal in the dataset that sleeps between 0 and 2 hours, and nine mammals that sleep two to four hours. Histograms are a great way to visually summarize the data, but we can use numerical summary statistics to summarize even further.\n\n**4. How long do mammals in this dataset typically sleep?**\n\nOne way we could summarize the data is by answering the question, How long do mammals in this dataset typically sleep? To answer this, we need to figure out what the \"typical\" or \"center\" value of the data is. We'll discuss three different definitions, or measures, of center: mean, median, and mode.\n\n**5. Measures of center: mean**\n\nThe mean, often called the average, is one of the most common ways of summarizing data. To calculate mean, we add up all the numbers of interest and divide by the total number of data points, which is 83 here. This gives us 10-point-43 hours of sleep. In R, we can use the mean function, passing it the variable of interest.\n\n**6. Measures of center: median**\n\nAnother measure of center is the median. The median is the value where 50% of the data is lower than it, and 50% of the data is higher. We can calculate this by sorting all the data points and taking the middle one, which would be index 42 in this case. This gives us a median of 10.1 hours of sleep. In R, we can use the median function to do the calculations for us.\n\n**7. Measures of center: mode**\n\nThe mode is the most frequent value in the data. If we count how many occurrences there are of each sleep_total and sort in descending order, there are 4 mammals that sleep for 12.5 hours, so this is the mode.The mode of the vore variable, which indicates the animal's diet, is herbivore. Mode is often used for categorical variables, since categorical variables can be unordered and often don't have an inherent numerical representation.\n\n**8. Adding an outlier**\n\nNow that we have lots of ways to measure center, how do we know which one to use? Let's look at an example. Here, we have all of the insectivores in the dataset.\n\n**9. Adding an outlier**\n\nWe get a mean sleep time of 16.5 hours and a median sleep time of 18.9 hours.\n\n**10. Adding an outlier**\n\nNow let's say we've discovered a new mystery insectivore that never sleeps.\n\n**11. Adding an outlier**\n\nIf we take the mean and median again, we get different results. The mean went down by more than 3 hours, while the median changed by less than an hour. This is because the mean is much more sensitive to extreme values than the median.\n\n**12. Which measure to use?**\n\nSince the mean is more sensitive to extreme values, it works better for symmetrical data like this. Notice that the mean, in red, and median, in blue, are quite close.\n\n**13. Skew**\n\nHowever, if the data is skewed, meaning it's not symmetrical, like this, median is usually better to use. In this histogram, the data is piled up on the right.\n\n**14. Skew**\n\nData that looks like this is called left-skewed data.\n\n**15. Skew**\n\nWhen data is piled up on the left, it's right-skewed.\n\n**16. Which measure to use?**\n\nWhen data is skewed, the mean and median are different. The mean is pulled in the direction of the skew, so it's lower than the median on the left-skewed data, and higher than the median on the right-skewed data. Because the mean is pulled around by the extreme values, it's better to use the median since it's less affected by outliers.\n\n**17. Let's practice!**\n\nLet's practice using measures of center.\n\n## Mean and median\n\nIn this chapter, you'll be working with the <a href=\"https://www.nu3.de/blogs/nutrition/food-carbon-footprint-index-2018\">2018 Food Carbon Footprint Index</a> from nu3. The `food_consumption` dataset contains information about the kilograms of food consumed per person per year in each country in each food category (`consumption`) as well as information about the carbon footprint of that food category (`co2_emissions`) measured in kilograms of carbon dioxide, or CO2, per person per year in each country.\n\nIn this exercise, you'll compute measures of center to compare food consumption in the US and Belgium using your `dplyr` skills. \n\n**Steps**\n\n1. Create two data frames: one that holds the rows of `food_consumption` for `\"Belgium\"` and the another that holds rows for `\"USA\"`. Call these `belgium_consumption` and `usa_consumption`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load packages\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> \n#> Attache Paket: 'dplyr'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Die folgenden Objekte sind maskiert von 'package:stats':\n#> \n#>     filter, lag\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n#> Die folgenden Objekte sind maskiert von 'package:base':\n#> \n#>     intersect, setdiff, setequal, union\n```\n:::\n\n```{.r .cell-code}\nfood_consumption <- readRDS(\"data/food_consumption.rds\")\n\n# 1.1 Filter for Belgium\nbelgium_consumption <- food_consumption |> \n  filter(country == \"Belgium\")\n\n# 1.2 Filter for USA\nusa_consumption <- food_consumption  |> \n  filter(country == \"USA\")\n```\n:::\n\n\n2. Calculate the mean and median of kilograms of food consumed per person per year for both countries.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2.1 Calculate mean and median consumption in Belgium\nmean(belgium_consumption$consumption)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 42.13273\n```\n:::\n\n```{.r .cell-code}\nmedian(belgium_consumption$consumption)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 12.59\n```\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2.2 Calculate mean and median consumption in USA\nmean(usa_consumption$consumption)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 44.65\n```\n:::\n\n```{.r .cell-code}\nmedian(usa_consumption$consumption)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 14.58\n```\n:::\n:::\n\n\n3. Filter `food_consumption` for rows with data about Belgium and the USA.\n4. Group the filtered data by `country`.\n5. Calculate the mean and median of the kilograms of food consumed per person per year in each country. Call these columns `mean_consumption` and `median_consumption`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfood_consumption  |> \n  # 3. Filter for Belgium and USA\n  filter(country %in% c(\"Belgium\", \"USA\"))  |> \n  # 4. Group by country\n  group_by(country)  |> \n  # 5. Get mean_consumption and median_consumption\n  summarise(mean_consumption   = mean(consumption),\n            median_consumption = median(consumption))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"mean_consumption\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"median_consumption\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Belgium\",\"2\":\"42.13273\",\"3\":\"12.59\"},{\"1\":\"USA\",\"2\":\"44.65000\",\"3\":\"14.58\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nMarvelous mean and median calculation! When you want to compare summary statistics between groups, it's much easier to do a `group_by()` and one `summarize()` instead of filtering and calling the same functions multiple times.\n\n## Mean vs. median\n\nIn the video, you learned that the mean is the sum of all the data points divided by the total number of data points, and the median is the middle value of the dataset where 50% of the data is less than the median, and 50% of the data is greater than the median. In this exercise, you'll compare these two measures of center.\n\n**Steps**\n\n1. Filter `food_consumption` to get the rows where `food_category` is `\"rice\"`.\n2. Create a histogram using `ggplot2` of `co2_emission` for rice.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Load packages\nlibrary(ggplot2)\n\nfood_consumption  |> \n  # 1. Filter for rice food category\n  filter(food_category == \"rice\")  |> \n  # 2. Create histogram of co2_emission\n  ggplot(aes(co2_emission)) +\n    geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n> *Question*\n> ---\n> Take a look at the histogram of the CO2 emissions for rice you just calculated. Which of the following terms best describes the shape of the data?<br>\n> <br>\n> ⬜ No skew<br>\n> ⬜ Left-skewed<br>\n> ✅ Right-skewed<br>\n\n3. Filter `food_consumption` to get the rows where `food_category` is `\"rice\"`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfood_consumption %>%\n  # Filter for rice food category\n  filter(food_category == \"rice\")  |> \n  # Create histogram of co2_emission\n  ggplot(aes(co2_emission)) +\n    geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-7-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n4. Summarize the data to get the mean and median of `co2_emission`, calling them `mean_co2` and `median_co2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfood_consumption  |> \n  # Filter for rice food category\n  filter(food_category == \"rice\") |> \n  # Get mean_co2 and median_co2\n  summarise(mean_co2   = mean(co2_emission),\n            median_co2 = median(co2_emission))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"mean_co2\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"median_co2\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"37.59162\",\"2\":\"15.2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n> *Question*\n> ---\n> Given the skew of this data, what measure of central tendency best summarizes the kilograms of CO2 emissions per person per year for rice?<br>\n> <br>\n> ⬜ Mean<br>\n> ✅ Median<br>\n> ⬜ Both mean and median<br>\n\nGreat work! The mean is substantially higher than the median since it's being pulled up by the high values over 100 kg/person/year.\n\n## Measures of spread\n\nTheory. Coming soon ...\n\n\n**1. Measures of spread**\n\nIn this lesson, we'll talk about another set of summary statistics: measures of spread.\n\n**2. What is spread?**\n\nSpread is just what it sounds like - it describes how spread apart or close together the data points are. Just like measures of center, there are a few different measures of spread.\n\n**3. Variance**\n\nThe first measure, variance, measures the average distance from each data point to the data's mean.\n\n**4. Variance**\n\nTo calculate the variance, we start by calculating the distance between each point and the mean, so we get one number for every data point.\n\n**5. Variance**\n\nWe then square each distance and then add them all together.\n\n**6. Variance**\n\nFinally, we divide the sum of squared distances by the number of data points minus 1, giving us the variance. The higher the variance, the more spread out the data is. It's important to note that the units of variance are squared, so in this case, it's 19.8 hours squared.We can calculate the variance in one step using the var function.\n\n**7. Standard deviation**\n\nThe standard deviation is another measure of spread, calculated by taking the square root of the variance. It can also be calculated using the sd function. The nice thing about standard deviation is that the units are usually easier to understand since they're not squared. It's easier to wrap your head around 4 and a half hours than 19.8 hours squared.\n\n**8. Mean absolute deviation**\n\nMean absolute deviation takes the absolute value of the distances to the mean, and then takes the mean of those differences. While this is similar to standard deviation, it's not exactly the same. Standard deviation squares distances, so longer distances are penalized more than shorter ones, while mean absolute deviation penalizes each distance equally. One isn't better than the other, but SD is more common than MAD.\n\n**9. Quartiles**\n\nBefore we discuss the next measure of spread, let's quickly talk about quartiles. Quartiles split up the data into four equal parts. Here, we call the quantile function to get the quartiles of the data. This means that 25% of the data is between 1-point-9 and 7-point-85, another 25% is between 7-point-85 and 10-point-10, and so on. This means that the second quartile splits the data in two, with 50% of the data below it and 50% of the data above it, so it's exactly the same as the median.\n\n**10. Boxplots use quartiles**\n\nThe boxes in box plots represent quartiles. The bottom of the box is the first quartile, and the top of the box is the third quartile. The middle line is the second quartile, or the median.\n\n**11. Quantiles**\n\nQuantiles, also called percentiles, are a generalized version of quartile, so they can split data into 5 pieces or ten pieces, for example. By default, the quantile function returns the quartiles of the data, but we can adjust this using the probs argument, which takes in a vector of proportions.Here, we split the data in five equal pieces. We can also use the seq function as a shortcut, which takes in the lowest number, the highest number, and the number we want to jump by. We can compute the same quantiles using seq from zero to one, jumping by 0-point-2.\n\n**12. Interquartile range (IQR)**\n\nThe interquartile range, or IQR, is another measure of spread. It's the distance between the 25th and 75th percentile, which is also the height of the box in a boxplot. We can calculate it using the quantile function to get 5-point-9 hours.\n\n**13. Outliers**\n\nOutliers are data points that are substantially different from the others. But how do we know what a substantial difference is?A rule that's often used is that any data point less than the first quartile minus 1.5 times the IQR is an outlier, as well as any point greater than the third quartile plus 1.5 times the IQR.\n\n**14. Finding outliers**\n\nTo find outliers, we'll start by calculating the IQR of the mammals' body weights. We can then calculate the lower and upper thresholds following the formulas from the previous slide.We can now filter the data frame to find mammals whose body weight is above or below the thresholds. We can see that there are eleven body weight outliers in this dataset, including the cow and the Asian elephant.\n\n**15. Let's practice!**\n\nTime to practice measuring spread and finding outliers.\n\n## Quartiles, quantiles, and quintiles\n\nQuantiles are a great way of summarizing numerical data since they can be used to measure center and spread, as well as to get a sense of where a data point stands in relation to the rest of the dataset. For example, you might want to give a discount to the 10% most active users on a website.\n\nIn this exercise, you'll calculate quartiles, quintiles, and deciles, which split up a dataset into 4, 5, and 10 pieces, respectively. \n\n**Steps**\n\n1. Calculate the quartiles of the `co2_emission` column of `food_consumption`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate the quartiles of co2_emission\nquantile(food_consumption$co2_emission)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>        0%       25%       50%       75%      100% \n#>    0.0000    5.2100   16.5300   62.5975 1712.0000\n```\n:::\n:::\n\n\n2. Calculate the six quantiles that split up the data into 5 pieces (quintiles) of the `co2_emission` column of `food_consumption`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate the quintiles of co2_emission\nquantile(food_consumption$co2_emission, probs = seq(0,1,0.2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>       0%      20%      40%      60%      80%     100% \n#>    0.000    3.540   11.026   25.590   99.978 1712.000\n```\n:::\n:::\n\n\n3. Calculate the eleven quantiles of `co2_emission` that split up the data into ten pieces (deciles).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate the deciles of co2_emission\nquantile(food_consumption$co2_emission, probs = seq(0,1,0.1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#>       0%      10%      20%      30%      40%      50%      60%      70% \n#>    0.000    0.668    3.540    7.040   11.026   16.530   25.590   44.271 \n#>      80%      90%     100% \n#>   99.978  203.629 1712.000\n```\n:::\n:::\n\n\nThose are some high-quality quantiles! While calculating more quantiles gives you a more detailed look at the data, it also produces more numbers, making the summary more difficult to quickly understand.\n\n## Variance and standard deviation\n\nVariance and standard deviation are two of the most common ways to measure the spread of a variable, and you'll practice calculating these in this exercise. Spread is important since it can help inform expectations. For example, if a salesperson sells a mean of 20 products a day, but has a standard deviation of 10 products, there will probably be days where they sell 40 products, but also days where they only sell one or two. Information like this is important, especially when making predictions.\n\nBoth `dplyr` and `ggplot2` are loaded, and `food_consumption` is available.\n\n**Steps**\n\n1. Calculate the variance and standard deviation of `co2_emission` for each `food_category` by grouping by and summarizing variance as `var_co2` and standard deviation as `sd_co2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Calculate variance and sd of co2_emission for each food_category\nfood_consumption %>% \n  group_by(food_category) %>% \n  summarise(var_co2 = var(co2_emission),\n     sd_co2 = sd(co2_emission))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"food_category\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"var_co2\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"sd_co2\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"beef\",\"2\":\"8.874841e+04\",\"3\":\"297.9067105\"},{\"1\":\"eggs\",\"2\":\"2.137182e+01\",\"3\":\"4.6229665\"},{\"1\":\"fish\",\"2\":\"9.216373e+02\",\"3\":\"30.3584807\"},{\"1\":\"lamb_goat\",\"2\":\"1.647552e+04\",\"3\":\"128.3569958\"},{\"1\":\"dairy\",\"2\":\"1.767189e+04\",\"3\":\"132.9356686\"},{\"1\":\"nuts\",\"2\":\"3.563965e+01\",\"3\":\"5.9698955\"},{\"1\":\"pork\",\"2\":\"3.094964e+03\",\"3\":\"55.6323965\"},{\"1\":\"poultry\",\"2\":\"2.450268e+02\",\"3\":\"15.6533320\"},{\"1\":\"rice\",\"2\":\"2.281376e+03\",\"3\":\"47.7637545\"},{\"1\":\"soybeans\",\"2\":\"8.798818e-01\",\"3\":\"0.9380202\"},{\"1\":\"wheat\",\"2\":\"7.102394e+01\",\"3\":\"8.4275700\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n2. Create a histogram of `co2_emission` for each `food_category` using `facet_wrap()`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. Plot food_consumption with co2_emission on x-axis\nggplot(food_consumption, aes(co2_emission)) +\n  # Create a histogram\n  geom_histogram() +\n  # Create a separate sub-graph for each food_category\n  facet_wrap(~ food_category)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-13-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nSuperb spread measurement! Beef has the biggest amount of variation in its CO$_2$ emissions, while eggs, nuts, and soybeans have relatively small amounts of variation.\n\n## Finding outliers using IQR\n\nOutliers can have big effects on statistics like mean, as well as statistics that rely on the mean, such as variance and standard deviation. Interquartile range, or IQR, is another way of measuring spread that's less influenced by outliers. IQR is also often used to find outliers. If a value is less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR, it's considered an outlier. In fact, this is how the lengths of the whiskers in a `ggplot2` box plot are calculated.\n\n<img src=\"https://assets.datacamp.com/production/repositories/5758/datasets/ca7e6e1832be7ec1842f62891815a9b0488efa83/Screen%20Shot%202020-04-28%20at%2010.04.54%20AM.png\" alt=\"Diagram of a box plot showing median, quartiles, and outliers\">\n\nIn this exercise, you'll calculate IQR and use it to find some outliers.\n\n**Steps**\n\n1. Calculate the total `co2_emission` per country by grouping by country and taking the sum of `co2_emission`. Call the sum `total_emission` and store the resulting data frame as `emissions_by_country`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate total co2_emission per country: emissions_by_country\nemissions_by_country <- food_consumption %>%\n  group_by(country) %>%\n  summarise(total_emission = sum(co2_emission))\n\nemissions_by_country\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"total_emission\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Albania\",\"2\":\"1777.85\"},{\"1\":\"Algeria\",\"2\":\"707.88\"},{\"1\":\"Angola\",\"2\":\"412.99\"},{\"1\":\"Argentina\",\"2\":\"2172.40\"},{\"1\":\"Armenia\",\"2\":\"1109.93\"},{\"1\":\"Australia\",\"2\":\"1938.66\"},{\"1\":\"Austria\",\"2\":\"1211.16\"},{\"1\":\"Bahamas\",\"2\":\"1192.90\"},{\"1\":\"Bangladesh\",\"2\":\"374.18\"},{\"1\":\"Barbados\",\"2\":\"889.11\"},{\"1\":\"Belarus\",\"2\":\"960.22\"},{\"1\":\"Belgium\",\"2\":\"1102.09\"},{\"1\":\"Belize\",\"2\":\"433.08\"},{\"1\":\"Bermuda\",\"2\":\"1483.28\"},{\"1\":\"Bolivia\",\"2\":\"873.03\"},{\"1\":\"Bosnia and Herzegovina\",\"2\":\"628.18\"},{\"1\":\"Botswana\",\"2\":\"576.84\"},{\"1\":\"Brazil\",\"2\":\"1616.73\"},{\"1\":\"Bulgaria\",\"2\":\"560.16\"},{\"1\":\"Cambodia\",\"2\":\"452.41\"},{\"1\":\"Cameroon\",\"2\":\"283.61\"},{\"1\":\"Canada\",\"2\":\"1437.16\"},{\"1\":\"Chile\",\"2\":\"1099.57\"},{\"1\":\"China\",\"2\":\"640.19\"},{\"1\":\"Colombia\",\"2\":\"781.53\"},{\"1\":\"Congo\",\"2\":\"262.55\"},{\"1\":\"Costa Rica\",\"2\":\"891.27\"},{\"1\":\"Croatia\",\"2\":\"996.15\"},{\"1\":\"Cuba\",\"2\":\"591.69\"},{\"1\":\"Cyprus\",\"2\":\"741.37\"},{\"1\":\"Czech Republic\",\"2\":\"760.09\"},{\"1\":\"Denmark\",\"2\":\"1498.18\"},{\"1\":\"Ecuador\",\"2\":\"883.88\"},{\"1\":\"Egypt\",\"2\":\"673.92\"},{\"1\":\"El Salvador\",\"2\":\"434.04\"},{\"1\":\"Estonia\",\"2\":\"830.72\"},{\"1\":\"Ethiopia\",\"2\":\"241.92\"},{\"1\":\"Fiji\",\"2\":\"716.09\"},{\"1\":\"Finland\",\"2\":\"1464.63\"},{\"1\":\"France\",\"2\":\"1420.05\"},{\"1\":\"French Polynesia\",\"2\":\"1424.69\"},{\"1\":\"Gambia\",\"2\":\"293.66\"},{\"1\":\"Georgia\",\"2\":\"527.03\"},{\"1\":\"Germany\",\"2\":\"1066.29\"},{\"1\":\"Ghana\",\"2\":\"217.87\"},{\"1\":\"Greece\",\"2\":\"1497.29\"},{\"1\":\"Grenada\",\"2\":\"439.85\"},{\"1\":\"Guatemala\",\"2\":\"314.98\"},{\"1\":\"Guinea\",\"2\":\"432.71\"},{\"1\":\"Honduras\",\"2\":\"434.08\"},{\"1\":\"Hong Kong SAR. China\",\"2\":\"1494.28\"},{\"1\":\"Hungary\",\"2\":\"576.79\"},{\"1\":\"Iceland\",\"2\":\"1731.36\"},{\"1\":\"India\",\"2\":\"282.62\"},{\"1\":\"Indonesia\",\"2\":\"367.51\"},{\"1\":\"Iran\",\"2\":\"445.27\"},{\"1\":\"Ireland\",\"2\":\"1459.67\"},{\"1\":\"Israel\",\"2\":\"1405.71\"},{\"1\":\"Italy\",\"2\":\"1206.33\"},{\"1\":\"Jamaica\",\"2\":\"450.83\"},{\"1\":\"Japan\",\"2\":\"644.04\"},{\"1\":\"Jordan\",\"2\":\"587.96\"},{\"1\":\"Kazakhstan\",\"2\":\"1575.08\"},{\"1\":\"Kenya\",\"2\":\"530.84\"},{\"1\":\"Kuwait\",\"2\":\"1345.44\"},{\"1\":\"Latvia\",\"2\":\"633.58\"},{\"1\":\"Liberia\",\"2\":\"203.38\"},{\"1\":\"Lithuania\",\"2\":\"868.90\"},{\"1\":\"Luxembourg\",\"2\":\"1598.41\"},{\"1\":\"Macedonia\",\"2\":\"600.75\"},{\"1\":\"Madagascar\",\"2\":\"440.75\"},{\"1\":\"Malawi\",\"2\":\"207.94\"},{\"1\":\"Malaysia\",\"2\":\"554.64\"},{\"1\":\"Maldives\",\"2\":\"903.46\"},{\"1\":\"Malta\",\"2\":\"1147.91\"},{\"1\":\"Mauritius\",\"2\":\"672.07\"},{\"1\":\"Mexico\",\"2\":\"797.13\"},{\"1\":\"Morocco\",\"2\":\"576.42\"},{\"1\":\"Mozambique\",\"2\":\"141.40\"},{\"1\":\"Myanmar\",\"2\":\"563.80\"},{\"1\":\"Namibia\",\"2\":\"362.11\"},{\"1\":\"Nepal\",\"2\":\"526.22\"},{\"1\":\"Netherlands\",\"2\":\"1292.82\"},{\"1\":\"New Caledonia\",\"2\":\"918.62\"},{\"1\":\"New Zealand\",\"2\":\"1750.95\"},{\"1\":\"Nicaragua\",\"2\":\"377.69\"},{\"1\":\"Niger\",\"2\":\"542.89\"},{\"1\":\"Nigeria\",\"2\":\"267.79\"},{\"1\":\"Norway\",\"2\":\"1381.89\"},{\"1\":\"Oman\",\"2\":\"1296.70\"},{\"1\":\"Pakistan\",\"2\":\"669.07\"},{\"1\":\"Panama\",\"2\":\"928.46\"},{\"1\":\"Paraguay\",\"2\":\"876.67\"},{\"1\":\"Peru\",\"2\":\"402.84\"},{\"1\":\"Philippines\",\"2\":\"455.28\"},{\"1\":\"Poland\",\"2\":\"607.40\"},{\"1\":\"Portugal\",\"2\":\"1174.28\"},{\"1\":\"Romania\",\"2\":\"766.30\"},{\"1\":\"Russia\",\"2\":\"1007.66\"},{\"1\":\"Rwanda\",\"2\":\"181.63\"},{\"1\":\"Saudi Arabia\",\"2\":\"692.86\"},{\"1\":\"Senegal\",\"2\":\"469.43\"},{\"1\":\"Serbia\",\"2\":\"723.34\"},{\"1\":\"Sierra Leone\",\"2\":\"300.41\"},{\"1\":\"Slovakia\",\"2\":\"560.34\"},{\"1\":\"Slovenia\",\"2\":\"1111.56\"},{\"1\":\"South Africa\",\"2\":\"892.41\"},{\"1\":\"South Korea\",\"2\":\"822.05\"},{\"1\":\"Spain\",\"2\":\"988.47\"},{\"1\":\"Sri Lanka\",\"2\":\"294.46\"},{\"1\":\"Swaziland\",\"2\":\"678.94\"},{\"1\":\"Sweden\",\"2\":\"1527.03\"},{\"1\":\"Switzerland\",\"2\":\"1356.75\"},{\"1\":\"Taiwan. ROC\",\"2\":\"559.55\"},{\"1\":\"Tanzania\",\"2\":\"343.02\"},{\"1\":\"Thailand\",\"2\":\"378.00\"},{\"1\":\"Togo\",\"2\":\"188.09\"},{\"1\":\"Trinidad and Tobago\",\"2\":\"610.41\"},{\"1\":\"Tunisia\",\"2\":\"618.89\"},{\"1\":\"Turkey\",\"2\":\"897.01\"},{\"1\":\"USA\",\"2\":\"1718.86\"},{\"1\":\"Uganda\",\"2\":\"304.72\"},{\"1\":\"Ukraine\",\"2\":\"665.73\"},{\"1\":\"United Arab Emirates\",\"2\":\"897.32\"},{\"1\":\"United Kingdom\",\"2\":\"1241.63\"},{\"1\":\"Uruguay\",\"2\":\"1634.91\"},{\"1\":\"Venezuela\",\"2\":\"1104.10\"},{\"1\":\"Vietnam\",\"2\":\"641.51\"},{\"1\":\"Zambia\",\"2\":\"225.30\"},{\"1\":\"Zimbabwe\",\"2\":\"350.33\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n2. Compute the first and third quartiles of `total_emission` and store these as `q1` and `q3`.\n3. Calculate the interquartile range of `total_emission` and store it as `iqr`.\n4. Calculate the lower and upper cutoffs for outliers of `total_emission`, and store these as `lower` and `upper`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. / 3. Compute the first and third quantiles and IQR of total_emission\nq1  <- quantile(emissions_by_country$total_emission, probs = 0.25)\nq3  <- quantile(emissions_by_country$total_emission, probs = 0.75)\niqr <- q3 - q1\n\n# Calculate the lower and upper cutoffs for outliers\nlower <- q1 - 1.5 * iqr\nupper <- q3 + 1.5 * iqr\n```\n:::\n\n\n5. Use `filter()` to get countries with a `total_emission` greater than the `upper` cutoff **or** a `total_emission` less than the `lower` cutoff.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 5. Filter emissions_by_country to find outliers\nemissions_by_country %>%\n  filter(total_emission > upper | total_emission < lower)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"country\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"total_emission\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Argentina\",\"2\":\"2172.4\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nOutstanding outlier detection! It looks like Argentina has a substantially higher amount of CO$_2$ emissions per person than other countries in the world.\n\n# 2. Random Numbers and Probability\n\nIn this chapter, you'll learn how to generate random samples and measure chance using probability. You'll work with real-world sales data to calculate the probability of a salesperson being successful. Finally, you’ll use the binomial distribution to model events with binary outcomes.\n\n## What are the chances?\n\nTheory. Coming soon ...\n\n\n**1. What are the chances?**\n\nPeople talk about chance pretty frequently, like what are the chances of closing a sale, of rain tomorrow, or of winning a game? But how exactly do we measure chance?\n\n**2. Measuring chance**\n\nWe can measure the chances of an event using probability. We can calculate the probability of some event by taking the number of ways the event can happen and dividing it by the total number of possible outcomes.For example, if we flip a coin, it can land on either heads or tails. To get the probability of the coin landing on heads, we divide the 1 way to get heads by the two possible outcomes, heads and tails. This gives us one half, or a fifty percent chance of getting heads.Probability is always between zero and 100 percent. If the probability of something is zero, it's impossible, and if the probability of something is 100%, it will certainly happen.\n\n**3. Assigning salespeople**\n\nLet's look at a more complex scenario. There's a meeting coming up with a potential client, and we want to send someone from the sales team to the meeting. We'll put each person's name on a ticket in a box and pull one out randomly to decide who goes to the meeting.\n\n**4. Assigning salespeople**\n\nBrian's name gets pulled out. The probability of Brian being selected is one out of four, or 25%.\n\n**5. Sampling from a data frame**\n\nWe can recreate this scenario in R using dplyr's sample_n function, which takes in a data frame and the number of rows we want to pull out, which is only 1 in this case.However, if we run the same thing again, we may get a different row since sample_n chooses randomly. If we want to show the team how we picked Brian, this won't work well.\n\n**6. Setting a random seed**\n\nTo ensure we get the same results when we run the script in front of the team, we'll set the random seed using set-dot-seed. The seed is a number that R's random number generator uses as a starting point, so if we orient it with a seed number, it will generate the same random value each time. The number itself doesn't matter. We could use 5, 139, or 3 million. The only thing that matters is that we use the same seed the next time we run the script. Now, we, or one of the sales-team members, can run this code over and over and get Brian every time.\n\n**7. A second meeting**\n\nNow there's another potential client who wants to meet at the same time, so we need to pick another salesperson. Brian already has been picked and he can't be in two meetings at once, so we'll pick between the remaining three. This is called sampling without replacement, since we aren't replacing the name we already pulled out.\n\n**8. A second meeting**\n\nThis time, Claire is picked, and the probability of this is one out of three, or about 33%.\n\n**9. Sampling twice in R**\n\nTo recreate this in R, we can pass 2 into sample_n, which will give us 2 rows.\n\n**10. Sampling with replacement**\n\nNow let's say the two meetings are happening on different days, so the same person could attend both. In this scenario, we need to return Brian's name to the box after picking it. This is called sampling with replacement.\n\n**11. Sampling with replacement**\n\nClaire gets picked for the second meeting, but this time, the probability of picking her is 25%.\n\n**12. Sampling with replacement in R**\n\nTo sample with replacement, set the replace argument of sample_n to TRUE.If there were 5 meetings, all at different times, it's possible to pick some rows multiple times since we're replacing them each time.\n\n**13. Independent events**\n\nLet's quickly talk about independence. Two events are independent if the probability of the second event isn't affected by the outcome of the first event. For example, if we're sampling with replacement, the probability\n\n**14. Independent events**\n\nthat Claire is picked second is 25%, no matter who gets picked first.In general, when sampling with replacement, each pick is independent.\n\n**15. Dependent events**\n\nSimilarly, events are considered dependent when the outcome of the first changes the probability of the second.If we sample without replacement, the probability that Claire is picked second depends on who gets picked first.\n\n**16. Dependent events**\n\nIf Claire is picked first, there's 0% probability that Claire will be picked second.\n\n**17. Dependent events**\n\nIf someone else is picked first, there's a 33% probability Claire will be picked second.In general, when sampling without replacement, each pick is dependent.\n\n**18. Let's practice!**\n\nHead over to the exercises!\n\n## With or without replacement?\n\nIn the video, you learned about two different ways of taking samples: with replacement and without replacement. Although it isn't always easy to tell which best fits various situations, it's important to correctly identify this so that any probabilities you report are accurate. In this exercise, you'll put your new knowledge to the test and practice figuring this out.\n\nFor each scenario, decide whether it's sampling with replacement or sampling without replacement.\n\n| With replacement | Without replacement |\n| --- | --- |\n| Flipping a coin 3 times | Randomly selecting 5 products from the assembly line to test for quality assurance |\n| Rolling a die twice | From a deck of cards, dealing 3 players 7 cards each | \n| | Randomly picking 3 people to work on the weekend from a group of 20 people | \n\n## Calculating probabilities\n\nYou're in charge of the sales team, and it's time for performance reviews, starting with Amir. As part of the review, you want to randomly select a few of the deals that he's worked on over the past year so that you can look at them more deeply. Before you start selecting deals, you'll first figure out what the chances are of selecting certain deals.\n\nRecall that the probability of an event can be calculated by\n\n<img src=\"https://render.githubusercontent.com/render/math?math={\\color{red}P(x)=\\frac{%23ways event can happen}{total %23 of possible outcomes}}\">\n\n**Steps**\n\n1. Count the number of deals Amir worked on for each `product` type.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\namir_deals <-  readRDS(\"data/amir_deals.rds\")\n\n# Count the deals for each product\namir_deals %>%\n  count(product, sort = T)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"product\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Product B\",\"2\":\"62\"},{\"1\":\"Product D\",\"2\":\"40\"},{\"1\":\"Product A\",\"2\":\"23\"},{\"1\":\"Product C\",\"2\":\"15\"},{\"1\":\"Product F\",\"2\":\"11\"},{\"1\":\"Product H\",\"2\":\"8\"},{\"1\":\"Product I\",\"2\":\"7\"},{\"1\":\"Product E\",\"2\":\"5\"},{\"1\":\"Product N\",\"2\":\"3\"},{\"1\":\"Product G\",\"2\":\"2\"},{\"1\":\"Product J\",\"2\":\"2\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n2. Create a new column called prob by dividing n by the total number of deals Amir worked on.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate probability of picking a deal with each product\namir_deals %>%\n  count(product, sort = T) %>%\n  mutate(prob = n/sum(n))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"product\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"prob\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Product B\",\"2\":\"62\",\"3\":\"0.34831461\"},{\"1\":\"Product D\",\"2\":\"40\",\"3\":\"0.22471910\"},{\"1\":\"Product A\",\"2\":\"23\",\"3\":\"0.12921348\"},{\"1\":\"Product C\",\"2\":\"15\",\"3\":\"0.08426966\"},{\"1\":\"Product F\",\"2\":\"11\",\"3\":\"0.06179775\"},{\"1\":\"Product H\",\"2\":\"8\",\"3\":\"0.04494382\"},{\"1\":\"Product I\",\"2\":\"7\",\"3\":\"0.03932584\"},{\"1\":\"Product E\",\"2\":\"5\",\"3\":\"0.02808989\"},{\"1\":\"Product N\",\"2\":\"3\",\"3\":\"0.01685393\"},{\"1\":\"Product G\",\"2\":\"2\",\"3\":\"0.01123596\"},{\"1\":\"Product J\",\"2\":\"2\",\"3\":\"0.01123596\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n> *Question*\n> ---\n> If you randomly select one of Amir's deals, what's the probability that the deal will involve Product C?<br>\n> <br>\n> ⬜ 15%<br>\n> ⬜ 80.43%<br>\n> ✅ 8.43%<br>\n> ⬜ 22.5%<br>\n\nPerfect probability calculations! Now that you know what the chances are, it's time to start sampling.\n\n## Sampling deals\n\nIn the previous exercise, you counted the deals Amir worked on. Now it's time to randomly pick five deals so that you can reach out to each customer and ask if they were satisfied with the service they received. You'll try doing this both with and without replacement.\n\nAdditionally, you want to make sure this is done randomly and that it can be reproduced in case you get asked how you chose the deals, so you'll need to set the random seed before sampling from the deals.\n\n**Steps**\n\n1. Set the random seed to `31`.\n2. Take a sample of 5 deals **without** replacement.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set random seed to 31\nset.seed(31)\n\n# Sample 5 deals without replacement\namir_deals %>%\n  sample_n(5)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"product\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"client\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"status\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"amount\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"num_users\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Product D\",\"2\":\"Current\",\"3\":\"Lost\",\"4\":\"3086.88\",\"5\":\"55\"},{\"1\":\"Product C\",\"2\":\"Current\",\"3\":\"Lost\",\"4\":\"3727.66\",\"5\":\"19\"},{\"1\":\"Product D\",\"2\":\"Current\",\"3\":\"Lost\",\"4\":\"4274.80\",\"5\":\"9\"},{\"1\":\"Product B\",\"2\":\"Current\",\"3\":\"Won\",\"4\":\"4965.08\",\"5\":\"9\"},{\"1\":\"Product A\",\"2\":\"Current\",\"3\":\"Won\",\"4\":\"5827.35\",\"5\":\"50\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n3. Take a sample of 5 deals **with** replacement.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set random seed to 31\nset.seed(31)\n\n# Sample 5 deals with replacement\namir_deals %>%\n  sample_n(5, replace = T)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"product\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"client\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"status\"],\"name\":[3],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"amount\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"num_users\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Product D\",\"2\":\"Current\",\"3\":\"Lost\",\"4\":\"3086.88\",\"5\":\"55\"},{\"1\":\"Product C\",\"2\":\"Current\",\"3\":\"Lost\",\"4\":\"3727.66\",\"5\":\"19\"},{\"1\":\"Product D\",\"2\":\"Current\",\"3\":\"Lost\",\"4\":\"4274.80\",\"5\":\"9\"},{\"1\":\"Product B\",\"2\":\"Current\",\"3\":\"Won\",\"4\":\"4965.08\",\"5\":\"9\"},{\"1\":\"Product A\",\"2\":\"Current\",\"3\":\"Won\",\"4\":\"5827.35\",\"5\":\"50\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n> *Question*\n> ---\n> What type of sampling is better to use for this situation?<br>\n> <br>\n> ⬜ With replacement<br>\n> ✅ Without replacement<br>\n> ⬜ It doesn't matter<br>\n\nSpectactular sampling! It's important to consider how you'll take a sample since there's no one-size-fits-all way to sample, and this can have an effect on your results.\n\n## Discrete distributions\n\nTheory. Coming soon ...\n\n\n**1. Discrete distributions**\n\nIn this lesson, we'll take a deeper dive into probability and begin looking at probability distributions.\n\n**2. Rolling the dice**\n\nLet's consider rolling a standard, six-sided die.\n\n**3. Rolling the dice**\n\nThere are six numbers, or six possible outcomes, and every number has one sixth, or about a 17 percent chance of being rolled. This is an example of a probability distribution.\n\n**4. Choosing salespeople**\n\nThis is similar to the scenario from earlier, except we had names instead of numbers. Just like rolling a die, each outcome, or name, had an equal chance of being chosen.\n\n**5. Probability distribution**\n\nA probability distribution describes the probability of each possible outcome in a scenario.We can also talk about the expected value of a distribution, which is the mean of a distribution. We can calculate this by multiplying each value by its probability (one sixth in this case) and summing, so the expected value of rolling a fair die is 3.5.\n\n**6. Visualizing a probability distribution**\n\nWe can visualize this using a barplot, where each bar represents an outcome, and each bar's height represents the probability of that outcome.\n\n**7. Probability = area**\n\nWe can calculate probabilities of different outcomes by taking areas of the probability distribution.For example, what's the probability that our die roll is less than or equal to 2? To figure this out, we'll take the area of each bar representing an outcome of 2 or less.\n\n**8. Probability = area**\n\nEach bar has a width of 1 and a height of one sixth, so the area of each bar is one sixth. We'll sum the areas for 1 and 2, to get a total probability of one third.\n\n**9. Uneven die**\n\nNow let's say we have a die where the two got turned into a three. This means that we now have a 0% chance of getting a 2, and a 33% chance of getting a 3. To calculate the expected value of this die, we now multiply 2 by 0, since it's impossible to get a 2, and 3 by its new probability, one third. This gives us an expected value that's slightly higher than the fair die.\n\n**10. Visualizing uneven probabilities**\n\nWhen we visualize these new probabilities, the bars are no longer even.\n\n**11. Adding areas**\n\nWith this die, what's the probability of getting something less than or equal to 2? There's a one sixth probability of getting 1, and zero probability of getting 2,\n\n**12. Adding areas**\n\nwhich sums to one sixth.\n\n**13. Discrete probability distributions**\n\nThe probability distributions you've seen so far are both discrete probability distributions, since they represent situations with discrete outcomes. Recall from chapter 1 that discrete variables can be thought of as counted variables. In the case of a die, we're counting dots, so we can't roll a 1-point-5 or 4-point-3.When all outcomes have the same probability, like a fair die, this is a special distribution called a discrete uniform distribution.\n\n**14. Sampling from discrete distributions**\n\nJust like we sampled names from a box, we can do the same thing with probability distributions like the ones we've seen. Here's a data frame called die that represents a fair die, and its expected value is 3-point-5.We'll sample from it 10 times to simulate 10 rolls. Notice that we sample with replacement so that we're sampling from the same distribution every time.\n\n**15. Visualizing a sample**\n\nWe can visualize the outcomes of the ten rolls using a histogram, setting the number of bins to 6 since there are 6 possible outcomes.\n\n**16. Sample distribution vs. theoretical distribution**\n\nNotice that we have different numbers of 1's, 2's, 3's, and so on since the sample was random, even though on each roll we had the same probability of rolling each number. The mean of our sample is 3-point-0, which isn't super close to the 3-point-5 we were expecting.\n\n**17. A bigger sample**\n\nIf we roll the die 100 times, the distribution of the rolls looks a bit more even, and the mean is closer to 3-point-5.\n\n**18. An even bigger sample**\n\nIf we roll 1000 times, it looks even more like the theoretical probability distribution and the mean closely matches 3-point-5.\n\n**19. Law of large numbers**\n\nThis is called the law of large numbers, which is the idea that as the size of your sample increases, the sample mean will approach the theoretical mean.\n\n**20. Let's practice!**\n\nTime to solidify your knowledge of probability distributions.\n\n## Creating a probability distribution\n\nA new restaurant opened a few months ago, and the restaurant's management wants to optimize its seating space based on the size of the groups that come most often. On one night, there are 10 groups of people waiting to be seated at the restaurant, but instead of being called in the order they arrived, they will be called randomly. In this exercise, you'll investigate the probability of groups of different sizes getting picked first. Data on each of the ten groups is contained in the `restaurant_groups` data frame.\n\nRemember that expected value can be calculated by multiplying each possible outcome with its corresponding probability and taking the sum.\n\n**Steps**\n\n1. Create a histogram of the `group_size` column of `restaurant_groups`, setting the number of bins to `5`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# restaurant groups\nrestaurant_groups <- tibble(\n  group_id   = c(1:10),\n  group_size = c(2, 4, 6, 2, 2, 2, 3, 2, 4, 2)\n)\n\n# 1. Create a histogram of group_size\nrestaurant_groups |> \n  ggplot(aes(group_size)) +\n    geom_histogram(bins = 5)\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-21-1.png){fig-align='center' width=672}\n:::\n:::\n\n2. Count the number of each `group_size` in `restaurant_groups`, then add a column called `probability` that contains the probability of randomly selecting a group of each size. Store this in a new data frame called `size_distribution`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. Create probability distribution\nsize_distribution <- restaurant_groups %>%\n  # Count number of each group size\n  count(group_size) %>%\n  # Calculate probability\n  mutate(probability = n / sum(n))\n\nsize_distribution\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"group_size\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"probability\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"2\",\"2\":\"6\",\"3\":\"0.6\"},{\"1\":\"3\",\"2\":\"1\",\"3\":\"0.1\"},{\"1\":\"4\",\"2\":\"2\",\"3\":\"0.2\"},{\"1\":\"6\",\"2\":\"1\",\"3\":\"0.1\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n3. Calculate the expected value of the `size_distribution`, which represents the expected group size.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 3. Calculate expected group size\nexpected_val <- sum(size_distribution$probability *\n                    size_distribution$group_size)\nexpected_val\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 2.9\n```\n:::\n:::\n\n\n4. Calculate the probability of randomly picking a group of 4 or more people by filtering and summarizing.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 4. Calculate probability of picking group of 4 or more\nsize_distribution %>%\n  # Filter for groups of 4 or larger\n  filter(group_size >= 4 ) %>%\n  # Calculate prob_4_or_more by taking sum of probabilities\n  summarise(prob_4_or_more = sum(probability))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"prob_4_or_more\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.3\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nDexterous distribution utilization! You'll continue to build upon these skills since many statistical tests and methods use probability distributions as their foundation.\n\n## Identifying distributions\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(patchwork)\np1 <- readRDS(\"data/p1.rds\"); p2 <- readRDS(\"data/p2.rds\"); p3 <- readRDS(\"data/p3.rds\")\np1 + p2 + p3\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-25-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n> *Question*\n> ---\n> Which sample is most likely to have been taken from a uniform distribution?<br>\n> <br>\n> ✅ A<br>\n> ⬜ B<br>\n> ⬜ C<br>\n\nImpressive identification! Since the histogram depicts a sample and not the actual probability distribution, each outcome won't happen the exact same number of times due to randomness, but they're similar in number.\n\n## Expected value vs. sample mean\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(purrr)\n\nsample_sizes <- c(10,100,1000,5000, 10000)\n\nsample_sizes |> \n  \n  # Set names, so that the data can be faceted according to the names\n  set_names() |> \n  # map rdunif against the sample sizes\n  map(rdunif, b = 9, a = 1) |> \n  map(as_tibble) |> \n  # Stack data\n  bind_rows(.id = \"sample_size\") |> \n  # Change order\n  mutate(sample_size = sample_size |> forcats::fct_inorder()) |> \n  # Plot\n  ggplot(aes(value)) + \n        geom_histogram(binwidth = 1) + \n        facet_wrap(~sample_size, scales = \"free\", nrow = 1)\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-26-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe code above will take a sample from a discrete uniform distribution, which includes the numbers 1 through 9, and calculate the sample's mean. You can adjust the size of the samples by changing the values of `sample_sizes`. Note that the expected value of this distribution is 5.\n\n> *Question*\n> ---\n> A sample is taken, and you win twenty dollars if the sample's mean is less than 4. There's a catch: you get to pick the sample's size. Which sample size is most likely to win you the twenty dollars?<br>\n> <br>\n> ✅ 10<br>\n> ⬜ 100<br>\n> ⬜ 1000<br>\n> ⬜ 5000<br>\n> ⬜ 10000<br>\n\nNice work! Since the sample mean will likely be closer to 5 (the expected value) with larger sample sizes, you have a better chance of getting a sample mean further away from 5 with a smaller sample. \n\n## Continuous distributions\n\nTheory. Coming soon ...\n\n\n**1. Continuous distributions**\n\nWe can use discrete distributions to model situations that involve discrete or countable variables, but how can we model continuous variables?\n\n**2. Waiting for the bus**\n\nLet's start with an example. The city bus arrives every twelve minutes, so if you show up at a random time, you could wait anywhere from 0 minutes if you arrive just as the bus pulls in, up to 12 minutes if you arrive as the bus leaves.\n\n**3. Continuous uniform distribution**\n\nLet's model this scenario with a probability distribution. There are an infinite number of minutes we could wait since we could wait 1 minute, 1-point-5 minutes, 1-point-53 minutes, and so on, so we can't create individual blocks like we could with a discrete variable.\n\n**4. Continuous uniform distribution**\n\nInstead, we'll use a continuous line to represent probability. The line is flat since there's the same probability of waiting any time from 0 to 12 minutes. This is called the continuous uniform distribution\n\n**5. Probability still = area**\n\nNow that we have our distribution, let's figure out what the probability is that we'll wait between 4 and 7 minutes. Just like with discrete distributions, we can take the area from 4 to 7 to calculate probability.\n\n**6. Probability still = area**\n\nThe width of this rectangle is 7 minus 4 which is 3. The height is one twelfth.\n\n**7. Probability still = area**\n\nMultiplying those together to get area, we get 3/12 or 25%.\n\n**8. Uniform distribution in R**\n\nLet's use the uniform distribution in R to calculate the probability of waiting 7 minutes or less. We'll pass 7 into punif. It also takes in a min and a max, which in our case is 0 and 12. The probability of waiting less than 7 minutes is about 58%.\n\n**9. lower.tail**\n\nIf we want the probability of waiting more than 7 minutes, set the lower-dot-tail argument to FALSE.\n\n**10. Combining multiple punif() calls**\n\nBut how do we calculate the probability of waiting 4 to 7 minutes using R?\n\n**11. Combining multiple punif() calls**\n\nWe can start with the probability of waiting less than 7 minutes,\n\n**12. Combining multiple punif() calls**\n\nthen subtract the probability of waiting less than 4 minutes. This gives us 25%.\n\n**13. Total area = 1**\n\nTo calculate the probability of waiting between 0 and 12 minutes, we multiply 12 by 1/12, which is 1.\n\n**14. Total area = 1**\n\nor 100%. This makes sense since we're certain we'll wait anywhere from 0 to 12 minutes.\n\n**15. Other continuous distributions**\n\nContinuous distributions can take forms other than uniform where some values have a higher probability than others.\n\n**16. Other continuous distributions**\n\nNo matter the shape of the distribution, the area beneath it must always equal 1.\n\n**17. Other special types of distributions**\n\nThis will also be true of other distributions you'll learn about later on in the course, like the normal distribution or Poisson distribution, which can be used to model many real-life situations.\n\n**18. Let's practice!**\n\nTime to practice working with continuous distributions.\n\n\n\n## Which distribution?\n\nAt this point, you've learned about the two different variants of the uniform distribution: the discrete uniform distribution, and the continuous uniform distribution. In this exercise, you'll decide which situations follow which distribution.\n\n<img src=\"https://assets.datacamp.com/production/repositories/5758/datasets/fe928d4c840f66544c6228b8b755e9bf15361b9f/Screen%20Shot%202020-05-04%20at%205.18.16%20PM.png\" alt=\"Illustration of discrete and continuous uniform distributions\">\n\n**Steps**\n\nMap each situation to the probability distribution it would best be modeled by.\n\n| Discrete Uniform | Continuous Unifrom | Other |\n| --- | --- | --- |\n| The ticket number of a raffle winner, assuming there is one ticket for each number from 1 to 100. | The time you'll have to wait for a geyser to erupt if you show up at a random time, knowing that the geyser erupts exactly every ten minutes. | The height of a random person. |\n| The outcome of rolling a 4-sided die. | The time of day a baby will be born. | |\n\n## Data back-ups\n\nThe sales software used at your company is set to automatically back itself up, but no one knows exactly what time the back-ups happen. It is known, however, that back-ups happen exactly every 30 minutes. Amir comes back from sales meetings at random times to update the data on the client he just met with. He wants to know how long he'll have to wait for his newly-entered data to get backed up. Use your new knowledge of continuous uniform distributions to model this situation and answer Amir's questions.\n\n**Steps**\n\n1. To model how long Amir will wait for a back-up using a continuous uniform distribution, save his lowest possible wait time as `min` and his longest possible wait time as `max`. Remember that back-ups happen every 30 minutes.\n2. Calculate the probability that Amir has to wait less than 5 minutes, and store in a variable called `prob_less_than_5`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Min and max wait times for back-up that happens every 30 min\nmin <- 0\nmax <- 30\n\n# 2. Calculate probability of waiting less than 5 mins\nprob_less_than_5 <- punif(5, min = min, max = max)\nprob_less_than_5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.1666667\n```\n:::\n:::\n\n\n3. Calculate the probability that Amir has to wait more than 5 minutes, and store in a variable called `prob_greater_than_5`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 3. Calculate probability of waiting more than 5 mins\nprob_greater_than_5 <- punif(5, min = min, max = max, lower.tail = F)\nprob_greater_than_5\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.8333333\n```\n:::\n:::\n\n\n4. Calculate the probability that Amir has to wait between 10 and 20 minutes, and store in a variable called `prob_between_10_and_20`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 4. Calculate probability of waiting 10-20 mins\nprob_between_10_and_20 <- punif(20, min = min, max = max) - punif(10, min = min, max = max)\nprob_between_10_and_20\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.3333333\n```\n:::\n:::\n\n\nWonderful wait-time calculations! There's a 33% chance that Amir will wait 10-20 minutes. In the next exercise, you'll make sure this calculation holds up by simulating some wait times.\n\n## Simulating wait times\n\nTo give Amir a better idea of how long he'll have to wait, you'll simulate Amir waiting 1000 times and create a histogram to show him what he should expect. Recall from the last exercise that his minimum wait time is 0 minutes and his maximum wait time is 30 minutes.\n\n**Steps**\n\n1. Set the random seed to `334`.\n2. Generate 1000 wait times from the continuous uniform distribution that models Amir's wait time. Add this as a new column called `time` in the `wait_times` data frame.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nwait_times <- tibble(simulation_nb=c(1:1000))\n\n# 1. Set random seed to 334\nset.seed(334)\n\n# 2. Generate 1000 wait times between 0 and 30 mins, save in time column\nwait_times %>%\n  mutate(time = runif(1000, min = 0, max = 30))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"simulation_nb\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"time\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"1\",\"2\":\"29.45315459\"},{\"1\":\"2\",\"2\":\"16.29111785\"},{\"1\":\"3\",\"2\":\"0.36924658\"},{\"1\":\"4\",\"2\":\"24.18677361\"},{\"1\":\"5\",\"2\":\"23.42601313\"},{\"1\":\"6\",\"2\":\"15.92492170\"},{\"1\":\"7\",\"2\":\"17.54207142\"},{\"1\":\"8\",\"2\":\"2.81082236\"},{\"1\":\"9\",\"2\":\"1.22953709\"},{\"1\":\"10\",\"2\":\"18.81465174\"},{\"1\":\"11\",\"2\":\"15.84175237\"},{\"1\":\"12\",\"2\":\"9.41775125\"},{\"1\":\"13\",\"2\":\"8.83677828\"},{\"1\":\"14\",\"2\":\"23.96499244\"},{\"1\":\"15\",\"2\":\"13.07967382\"},{\"1\":\"16\",\"2\":\"4.01695817\"},{\"1\":\"17\",\"2\":\"7.99449634\"},{\"1\":\"18\",\"2\":\"4.58148719\"},{\"1\":\"19\",\"2\":\"14.70777321\"},{\"1\":\"20\",\"2\":\"25.78698850\"},{\"1\":\"21\",\"2\":\"29.99619469\"},{\"1\":\"22\",\"2\":\"18.16970525\"},{\"1\":\"23\",\"2\":\"14.09443719\"},{\"1\":\"24\",\"2\":\"12.61347899\"},{\"1\":\"25\",\"2\":\"12.29471693\"},{\"1\":\"26\",\"2\":\"1.71292025\"},{\"1\":\"27\",\"2\":\"16.78696537\"},{\"1\":\"28\",\"2\":\"17.82353542\"},{\"1\":\"29\",\"2\":\"5.68281747\"},{\"1\":\"30\",\"2\":\"22.49724553\"},{\"1\":\"31\",\"2\":\"11.25188137\"},{\"1\":\"32\",\"2\":\"19.08385771\"},{\"1\":\"33\",\"2\":\"0.05211500\"},{\"1\":\"34\",\"2\":\"0.29523587\"},{\"1\":\"35\",\"2\":\"24.78207979\"},{\"1\":\"36\",\"2\":\"24.27452489\"},{\"1\":\"37\",\"2\":\"12.58902050\"},{\"1\":\"38\",\"2\":\"7.31610345\"},{\"1\":\"39\",\"2\":\"21.98134186\"},{\"1\":\"40\",\"2\":\"1.44244587\"},{\"1\":\"41\",\"2\":\"16.48523526\"},{\"1\":\"42\",\"2\":\"18.47448285\"},{\"1\":\"43\",\"2\":\"28.68268560\"},{\"1\":\"44\",\"2\":\"16.51950021\"},{\"1\":\"45\",\"2\":\"26.10806020\"},{\"1\":\"46\",\"2\":\"25.44633436\"},{\"1\":\"47\",\"2\":\"27.31116007\"},{\"1\":\"48\",\"2\":\"16.78878267\"},{\"1\":\"49\",\"2\":\"4.59194899\"},{\"1\":\"50\",\"2\":\"25.07935484\"},{\"1\":\"51\",\"2\":\"19.51173451\"},{\"1\":\"52\",\"2\":\"23.75916684\"},{\"1\":\"53\",\"2\":\"22.00560742\"},{\"1\":\"54\",\"2\":\"23.85031574\"},{\"1\":\"55\",\"2\":\"5.17543838\"},{\"1\":\"56\",\"2\":\"5.22998160\"},{\"1\":\"57\",\"2\":\"15.10675023\"},{\"1\":\"58\",\"2\":\"19.09363108\"},{\"1\":\"59\",\"2\":\"16.93706591\"},{\"1\":\"60\",\"2\":\"22.65432542\"},{\"1\":\"61\",\"2\":\"23.89705532\"},{\"1\":\"62\",\"2\":\"8.72819969\"},{\"1\":\"63\",\"2\":\"8.44010386\"},{\"1\":\"64\",\"2\":\"28.33278771\"},{\"1\":\"65\",\"2\":\"21.83944697\"},{\"1\":\"66\",\"2\":\"10.93783317\"},{\"1\":\"67\",\"2\":\"27.76403802\"},{\"1\":\"68\",\"2\":\"2.56605274\"},{\"1\":\"69\",\"2\":\"1.22772286\"},{\"1\":\"70\",\"2\":\"26.77751457\"},{\"1\":\"71\",\"2\":\"16.04902673\"},{\"1\":\"72\",\"2\":\"11.37484696\"},{\"1\":\"73\",\"2\":\"17.39148053\"},{\"1\":\"74\",\"2\":\"21.88181105\"},{\"1\":\"75\",\"2\":\"2.09128249\"},{\"1\":\"76\",\"2\":\"2.31436525\"},{\"1\":\"77\",\"2\":\"8.61378860\"},{\"1\":\"78\",\"2\":\"18.21443749\"},{\"1\":\"79\",\"2\":\"14.50121775\"},{\"1\":\"80\",\"2\":\"7.34539799\"},{\"1\":\"81\",\"2\":\"25.34504854\"},{\"1\":\"82\",\"2\":\"22.62102517\"},{\"1\":\"83\",\"2\":\"17.53644251\"},{\"1\":\"84\",\"2\":\"21.02231852\"},{\"1\":\"85\",\"2\":\"26.09942971\"},{\"1\":\"86\",\"2\":\"13.48281613\"},{\"1\":\"87\",\"2\":\"21.73122370\"},{\"1\":\"88\",\"2\":\"24.38144228\"},{\"1\":\"89\",\"2\":\"29.51306323\"},{\"1\":\"90\",\"2\":\"26.85805804\"},{\"1\":\"91\",\"2\":\"7.09091901\"},{\"1\":\"92\",\"2\":\"13.55704284\"},{\"1\":\"93\",\"2\":\"4.64813914\"},{\"1\":\"94\",\"2\":\"11.72299788\"},{\"1\":\"95\",\"2\":\"29.16724531\"},{\"1\":\"96\",\"2\":\"2.56408873\"},{\"1\":\"97\",\"2\":\"19.96485271\"},{\"1\":\"98\",\"2\":\"26.84800347\"},{\"1\":\"99\",\"2\":\"1.98970109\"},{\"1\":\"100\",\"2\":\"27.80477462\"},{\"1\":\"101\",\"2\":\"4.68890270\"},{\"1\":\"102\",\"2\":\"29.75399736\"},{\"1\":\"103\",\"2\":\"28.86156492\"},{\"1\":\"104\",\"2\":\"1.62335933\"},{\"1\":\"105\",\"2\":\"26.58146717\"},{\"1\":\"106\",\"2\":\"6.95498544\"},{\"1\":\"107\",\"2\":\"24.37387391\"},{\"1\":\"108\",\"2\":\"20.63972661\"},{\"1\":\"109\",\"2\":\"3.31054327\"},{\"1\":\"110\",\"2\":\"15.24809941\"},{\"1\":\"111\",\"2\":\"16.66182927\"},{\"1\":\"112\",\"2\":\"21.08719027\"},{\"1\":\"113\",\"2\":\"2.13087585\"},{\"1\":\"114\",\"2\":\"5.50382916\"},{\"1\":\"115\",\"2\":\"2.18534266\"},{\"1\":\"116\",\"2\":\"16.72306163\"},{\"1\":\"117\",\"2\":\"15.27638286\"},{\"1\":\"118\",\"2\":\"21.93987240\"},{\"1\":\"119\",\"2\":\"8.14819436\"},{\"1\":\"120\",\"2\":\"13.22942961\"},{\"1\":\"121\",\"2\":\"4.81524780\"},{\"1\":\"122\",\"2\":\"4.63081524\"},{\"1\":\"123\",\"2\":\"3.90025639\"},{\"1\":\"124\",\"2\":\"12.27260683\"},{\"1\":\"125\",\"2\":\"13.50092378\"},{\"1\":\"126\",\"2\":\"8.49478288\"},{\"1\":\"127\",\"2\":\"1.31813536\"},{\"1\":\"128\",\"2\":\"18.35409017\"},{\"1\":\"129\",\"2\":\"19.33882381\"},{\"1\":\"130\",\"2\":\"3.67552059\"},{\"1\":\"131\",\"2\":\"10.96036061\"},{\"1\":\"132\",\"2\":\"17.36368593\"},{\"1\":\"133\",\"2\":\"9.11544772\"},{\"1\":\"134\",\"2\":\"20.69915994\"},{\"1\":\"135\",\"2\":\"27.80066973\"},{\"1\":\"136\",\"2\":\"9.96377338\"},{\"1\":\"137\",\"2\":\"24.10210552\"},{\"1\":\"138\",\"2\":\"8.26637429\"},{\"1\":\"139\",\"2\":\"22.07137189\"},{\"1\":\"140\",\"2\":\"15.21410348\"},{\"1\":\"141\",\"2\":\"7.70470032\"},{\"1\":\"142\",\"2\":\"24.57876420\"},{\"1\":\"143\",\"2\":\"5.11461786\"},{\"1\":\"144\",\"2\":\"20.73345027\"},{\"1\":\"145\",\"2\":\"8.30975461\"},{\"1\":\"146\",\"2\":\"16.99033177\"},{\"1\":\"147\",\"2\":\"26.57024723\"},{\"1\":\"148\",\"2\":\"18.91592598\"},{\"1\":\"149\",\"2\":\"20.11793115\"},{\"1\":\"150\",\"2\":\"25.66186169\"},{\"1\":\"151\",\"2\":\"3.30988693\"},{\"1\":\"152\",\"2\":\"12.44513940\"},{\"1\":\"153\",\"2\":\"3.90224391\"},{\"1\":\"154\",\"2\":\"13.82439813\"},{\"1\":\"155\",\"2\":\"14.13531585\"},{\"1\":\"156\",\"2\":\"13.10707968\"},{\"1\":\"157\",\"2\":\"21.15397943\"},{\"1\":\"158\",\"2\":\"10.74559600\"},{\"1\":\"159\",\"2\":\"22.55146616\"},{\"1\":\"160\",\"2\":\"21.56216869\"},{\"1\":\"161\",\"2\":\"1.36846875\"},{\"1\":\"162\",\"2\":\"4.44459092\"},{\"1\":\"163\",\"2\":\"0.47738479\"},{\"1\":\"164\",\"2\":\"15.44300649\"},{\"1\":\"165\",\"2\":\"13.61435918\"},{\"1\":\"166\",\"2\":\"14.59740393\"},{\"1\":\"167\",\"2\":\"18.13859917\"},{\"1\":\"168\",\"2\":\"4.90525077\"},{\"1\":\"169\",\"2\":\"24.78090435\"},{\"1\":\"170\",\"2\":\"18.75689236\"},{\"1\":\"171\",\"2\":\"4.70107029\"},{\"1\":\"172\",\"2\":\"25.96421457\"},{\"1\":\"173\",\"2\":\"21.05015198\"},{\"1\":\"174\",\"2\":\"20.60453370\"},{\"1\":\"175\",\"2\":\"28.19999088\"},{\"1\":\"176\",\"2\":\"27.77331149\"},{\"1\":\"177\",\"2\":\"22.88689508\"},{\"1\":\"178\",\"2\":\"23.77027513\"},{\"1\":\"179\",\"2\":\"19.82064425\"},{\"1\":\"180\",\"2\":\"13.67029054\"},{\"1\":\"181\",\"2\":\"19.86780181\"},{\"1\":\"182\",\"2\":\"5.09980166\"},{\"1\":\"183\",\"2\":\"20.09009174\"},{\"1\":\"184\",\"2\":\"9.19944863\"},{\"1\":\"185\",\"2\":\"3.47489387\"},{\"1\":\"186\",\"2\":\"7.87616526\"},{\"1\":\"187\",\"2\":\"15.94566443\"},{\"1\":\"188\",\"2\":\"10.17268332\"},{\"1\":\"189\",\"2\":\"17.05031343\"},{\"1\":\"190\",\"2\":\"27.05733098\"},{\"1\":\"191\",\"2\":\"27.02909490\"},{\"1\":\"192\",\"2\":\"2.83697048\"},{\"1\":\"193\",\"2\":\"7.85712880\"},{\"1\":\"194\",\"2\":\"18.33081177\"},{\"1\":\"195\",\"2\":\"10.23665127\"},{\"1\":\"196\",\"2\":\"26.60579928\"},{\"1\":\"197\",\"2\":\"23.83012579\"},{\"1\":\"198\",\"2\":\"9.70762531\"},{\"1\":\"199\",\"2\":\"3.94041099\"},{\"1\":\"200\",\"2\":\"22.12165447\"},{\"1\":\"201\",\"2\":\"10.68154077\"},{\"1\":\"202\",\"2\":\"0.76626179\"},{\"1\":\"203\",\"2\":\"7.09016587\"},{\"1\":\"204\",\"2\":\"4.05329900\"},{\"1\":\"205\",\"2\":\"0.83210992\"},{\"1\":\"206\",\"2\":\"18.85119532\"},{\"1\":\"207\",\"2\":\"4.35439821\"},{\"1\":\"208\",\"2\":\"0.64977399\"},{\"1\":\"209\",\"2\":\"25.84636275\"},{\"1\":\"210\",\"2\":\"15.84230244\"},{\"1\":\"211\",\"2\":\"25.86542755\"},{\"1\":\"212\",\"2\":\"26.07684359\"},{\"1\":\"213\",\"2\":\"6.18999966\"},{\"1\":\"214\",\"2\":\"8.43593902\"},{\"1\":\"215\",\"2\":\"24.18478795\"},{\"1\":\"216\",\"2\":\"10.62778520\"},{\"1\":\"217\",\"2\":\"17.19132731\"},{\"1\":\"218\",\"2\":\"11.31612540\"},{\"1\":\"219\",\"2\":\"27.80950904\"},{\"1\":\"220\",\"2\":\"7.08353750\"},{\"1\":\"221\",\"2\":\"22.54112792\"},{\"1\":\"222\",\"2\":\"22.89749492\"},{\"1\":\"223\",\"2\":\"14.78477028\"},{\"1\":\"224\",\"2\":\"14.04549201\"},{\"1\":\"225\",\"2\":\"14.93056498\"},{\"1\":\"226\",\"2\":\"15.61904760\"},{\"1\":\"227\",\"2\":\"27.90506173\"},{\"1\":\"228\",\"2\":\"29.03126386\"},{\"1\":\"229\",\"2\":\"17.95046012\"},{\"1\":\"230\",\"2\":\"9.50867706\"},{\"1\":\"231\",\"2\":\"28.96867423\"},{\"1\":\"232\",\"2\":\"17.23006020\"},{\"1\":\"233\",\"2\":\"16.48326953\"},{\"1\":\"234\",\"2\":\"29.62941040\"},{\"1\":\"235\",\"2\":\"29.53264363\"},{\"1\":\"236\",\"2\":\"13.06570023\"},{\"1\":\"237\",\"2\":\"5.51182835\"},{\"1\":\"238\",\"2\":\"8.97947283\"},{\"1\":\"239\",\"2\":\"6.95682119\"},{\"1\":\"240\",\"2\":\"13.94301978\"},{\"1\":\"241\",\"2\":\"5.88415202\"},{\"1\":\"242\",\"2\":\"29.99165510\"},{\"1\":\"243\",\"2\":\"27.53866999\"},{\"1\":\"244\",\"2\":\"17.52703829\"},{\"1\":\"245\",\"2\":\"28.10205803\"},{\"1\":\"246\",\"2\":\"7.26896494\"},{\"1\":\"247\",\"2\":\"5.85534172\"},{\"1\":\"248\",\"2\":\"19.06698948\"},{\"1\":\"249\",\"2\":\"25.44289668\"},{\"1\":\"250\",\"2\":\"13.32176088\"},{\"1\":\"251\",\"2\":\"6.08293406\"},{\"1\":\"252\",\"2\":\"10.95717730\"},{\"1\":\"253\",\"2\":\"15.72299918\"},{\"1\":\"254\",\"2\":\"6.05257920\"},{\"1\":\"255\",\"2\":\"10.13583530\"},{\"1\":\"256\",\"2\":\"16.32800652\"},{\"1\":\"257\",\"2\":\"0.50360160\"},{\"1\":\"258\",\"2\":\"24.69565599\"},{\"1\":\"259\",\"2\":\"19.79090953\"},{\"1\":\"260\",\"2\":\"6.41763006\"},{\"1\":\"261\",\"2\":\"21.39276288\"},{\"1\":\"262\",\"2\":\"15.25108414\"},{\"1\":\"263\",\"2\":\"16.11735773\"},{\"1\":\"264\",\"2\":\"24.61424236\"},{\"1\":\"265\",\"2\":\"24.08914387\"},{\"1\":\"266\",\"2\":\"14.65908080\"},{\"1\":\"267\",\"2\":\"1.53653435\"},{\"1\":\"268\",\"2\":\"21.94335671\"},{\"1\":\"269\",\"2\":\"7.29698789\"},{\"1\":\"270\",\"2\":\"25.79171011\"},{\"1\":\"271\",\"2\":\"13.81756713\"},{\"1\":\"272\",\"2\":\"1.52692696\"},{\"1\":\"273\",\"2\":\"28.68397699\"},{\"1\":\"274\",\"2\":\"24.44759800\"},{\"1\":\"275\",\"2\":\"18.47182235\"},{\"1\":\"276\",\"2\":\"9.82464750\"},{\"1\":\"277\",\"2\":\"7.37684553\"},{\"1\":\"278\",\"2\":\"27.34689845\"},{\"1\":\"279\",\"2\":\"11.81990997\"},{\"1\":\"280\",\"2\":\"18.56640825\"},{\"1\":\"281\",\"2\":\"28.41001900\"},{\"1\":\"282\",\"2\":\"3.69871438\"},{\"1\":\"283\",\"2\":\"21.62252435\"},{\"1\":\"284\",\"2\":\"29.01304065\"},{\"1\":\"285\",\"2\":\"21.17122008\"},{\"1\":\"286\",\"2\":\"9.23375448\"},{\"1\":\"287\",\"2\":\"9.28087743\"},{\"1\":\"288\",\"2\":\"9.11876739\"},{\"1\":\"289\",\"2\":\"14.28881688\"},{\"1\":\"290\",\"2\":\"27.64225040\"},{\"1\":\"291\",\"2\":\"29.12166760\"},{\"1\":\"292\",\"2\":\"14.81106031\"},{\"1\":\"293\",\"2\":\"19.26581445\"},{\"1\":\"294\",\"2\":\"2.18942036\"},{\"1\":\"295\",\"2\":\"13.09335056\"},{\"1\":\"296\",\"2\":\"19.36590429\"},{\"1\":\"297\",\"2\":\"20.83139085\"},{\"1\":\"298\",\"2\":\"14.47464931\"},{\"1\":\"299\",\"2\":\"22.82562831\"},{\"1\":\"300\",\"2\":\"27.00556817\"},{\"1\":\"301\",\"2\":\"6.12020946\"},{\"1\":\"302\",\"2\":\"26.50418573\"},{\"1\":\"303\",\"2\":\"2.33169044\"},{\"1\":\"304\",\"2\":\"18.21444613\"},{\"1\":\"305\",\"2\":\"17.73878159\"},{\"1\":\"306\",\"2\":\"0.88235375\"},{\"1\":\"307\",\"2\":\"3.94441641\"},{\"1\":\"308\",\"2\":\"7.16087096\"},{\"1\":\"309\",\"2\":\"19.83257173\"},{\"1\":\"310\",\"2\":\"21.29177334\"},{\"1\":\"311\",\"2\":\"14.23450629\"},{\"1\":\"312\",\"2\":\"15.29842467\"},{\"1\":\"313\",\"2\":\"2.49413843\"},{\"1\":\"314\",\"2\":\"19.13876231\"},{\"1\":\"315\",\"2\":\"23.24597251\"},{\"1\":\"316\",\"2\":\"17.85439791\"},{\"1\":\"317\",\"2\":\"16.83771461\"},{\"1\":\"318\",\"2\":\"10.20920923\"},{\"1\":\"319\",\"2\":\"10.30384726\"},{\"1\":\"320\",\"2\":\"2.80929160\"},{\"1\":\"321\",\"2\":\"26.55758000\"},{\"1\":\"322\",\"2\":\"29.83452890\"},{\"1\":\"323\",\"2\":\"10.94769653\"},{\"1\":\"324\",\"2\":\"13.64371708\"},{\"1\":\"325\",\"2\":\"27.14646269\"},{\"1\":\"326\",\"2\":\"11.73016779\"},{\"1\":\"327\",\"2\":\"23.42090358\"},{\"1\":\"328\",\"2\":\"18.68195778\"},{\"1\":\"329\",\"2\":\"6.77623506\"},{\"1\":\"330\",\"2\":\"4.32711476\"},{\"1\":\"331\",\"2\":\"26.58448611\"},{\"1\":\"332\",\"2\":\"20.53492705\"},{\"1\":\"333\",\"2\":\"21.78986641\"},{\"1\":\"334\",\"2\":\"19.78927551\"},{\"1\":\"335\",\"2\":\"9.16987331\"},{\"1\":\"336\",\"2\":\"25.49647434\"},{\"1\":\"337\",\"2\":\"12.95142716\"},{\"1\":\"338\",\"2\":\"9.21591724\"},{\"1\":\"339\",\"2\":\"3.71928454\"},{\"1\":\"340\",\"2\":\"10.18400854\"},{\"1\":\"341\",\"2\":\"13.81445620\"},{\"1\":\"342\",\"2\":\"18.75217533\"},{\"1\":\"343\",\"2\":\"3.04595439\"},{\"1\":\"344\",\"2\":\"10.79786948\"},{\"1\":\"345\",\"2\":\"29.31001355\"},{\"1\":\"346\",\"2\":\"1.21589832\"},{\"1\":\"347\",\"2\":\"16.71420172\"},{\"1\":\"348\",\"2\":\"7.01302179\"},{\"1\":\"349\",\"2\":\"2.50405112\"},{\"1\":\"350\",\"2\":\"14.31464099\"},{\"1\":\"351\",\"2\":\"23.06294401\"},{\"1\":\"352\",\"2\":\"14.79304570\"},{\"1\":\"353\",\"2\":\"17.88536563\"},{\"1\":\"354\",\"2\":\"10.09426212\"},{\"1\":\"355\",\"2\":\"28.05442481\"},{\"1\":\"356\",\"2\":\"21.08625339\"},{\"1\":\"357\",\"2\":\"17.73074598\"},{\"1\":\"358\",\"2\":\"22.54238734\"},{\"1\":\"359\",\"2\":\"18.68309828\"},{\"1\":\"360\",\"2\":\"9.12667959\"},{\"1\":\"361\",\"2\":\"6.78268570\"},{\"1\":\"362\",\"2\":\"12.87106037\"},{\"1\":\"363\",\"2\":\"13.27456597\"},{\"1\":\"364\",\"2\":\"11.96363262\"},{\"1\":\"365\",\"2\":\"7.82005662\"},{\"1\":\"366\",\"2\":\"14.76887760\"},{\"1\":\"367\",\"2\":\"25.22041113\"},{\"1\":\"368\",\"2\":\"28.75726938\"},{\"1\":\"369\",\"2\":\"4.62506805\"},{\"1\":\"370\",\"2\":\"8.21708702\"},{\"1\":\"371\",\"2\":\"14.27739504\"},{\"1\":\"372\",\"2\":\"5.19841835\"},{\"1\":\"373\",\"2\":\"29.14449930\"},{\"1\":\"374\",\"2\":\"7.17904563\"},{\"1\":\"375\",\"2\":\"21.33901682\"},{\"1\":\"376\",\"2\":\"9.15599429\"},{\"1\":\"377\",\"2\":\"29.91129147\"},{\"1\":\"378\",\"2\":\"7.24296600\"},{\"1\":\"379\",\"2\":\"0.56037860\"},{\"1\":\"380\",\"2\":\"2.84814615\"},{\"1\":\"381\",\"2\":\"1.77340397\"},{\"1\":\"382\",\"2\":\"21.86930791\"},{\"1\":\"383\",\"2\":\"2.43868958\"},{\"1\":\"384\",\"2\":\"13.71335877\"},{\"1\":\"385\",\"2\":\"22.65005260\"},{\"1\":\"386\",\"2\":\"2.35276919\"},{\"1\":\"387\",\"2\":\"6.99185851\"},{\"1\":\"388\",\"2\":\"16.07555050\"},{\"1\":\"389\",\"2\":\"1.66261677\"},{\"1\":\"390\",\"2\":\"18.19484275\"},{\"1\":\"391\",\"2\":\"19.43370478\"},{\"1\":\"392\",\"2\":\"8.45190485\"},{\"1\":\"393\",\"2\":\"5.64412612\"},{\"1\":\"394\",\"2\":\"27.98906704\"},{\"1\":\"395\",\"2\":\"22.63233759\"},{\"1\":\"396\",\"2\":\"25.22347289\"},{\"1\":\"397\",\"2\":\"13.63546245\"},{\"1\":\"398\",\"2\":\"7.64288333\"},{\"1\":\"399\",\"2\":\"15.19147471\"},{\"1\":\"400\",\"2\":\"2.91592826\"},{\"1\":\"401\",\"2\":\"7.02979135\"},{\"1\":\"402\",\"2\":\"17.54522154\"},{\"1\":\"403\",\"2\":\"9.56778450\"},{\"1\":\"404\",\"2\":\"2.31630396\"},{\"1\":\"405\",\"2\":\"9.02047624\"},{\"1\":\"406\",\"2\":\"9.19811845\"},{\"1\":\"407\",\"2\":\"29.74029722\"},{\"1\":\"408\",\"2\":\"27.20223204\"},{\"1\":\"409\",\"2\":\"5.07001682\"},{\"1\":\"410\",\"2\":\"6.42362910\"},{\"1\":\"411\",\"2\":\"10.36749214\"},{\"1\":\"412\",\"2\":\"17.06248441\"},{\"1\":\"413\",\"2\":\"14.09376311\"},{\"1\":\"414\",\"2\":\"20.99937669\"},{\"1\":\"415\",\"2\":\"19.15727428\"},{\"1\":\"416\",\"2\":\"6.19942550\"},{\"1\":\"417\",\"2\":\"18.63208443\"},{\"1\":\"418\",\"2\":\"11.16741173\"},{\"1\":\"419\",\"2\":\"12.83131198\"},{\"1\":\"420\",\"2\":\"14.85977447\"},{\"1\":\"421\",\"2\":\"13.66304567\"},{\"1\":\"422\",\"2\":\"19.83423738\"},{\"1\":\"423\",\"2\":\"4.01754856\"},{\"1\":\"424\",\"2\":\"27.47191604\"},{\"1\":\"425\",\"2\":\"23.92742818\"},{\"1\":\"426\",\"2\":\"18.87272294\"},{\"1\":\"427\",\"2\":\"26.66857070\"},{\"1\":\"428\",\"2\":\"0.15995986\"},{\"1\":\"429\",\"2\":\"16.22308373\"},{\"1\":\"430\",\"2\":\"13.42008427\"},{\"1\":\"431\",\"2\":\"16.17911689\"},{\"1\":\"432\",\"2\":\"10.01260702\"},{\"1\":\"433\",\"2\":\"28.56098204\"},{\"1\":\"434\",\"2\":\"25.75032657\"},{\"1\":\"435\",\"2\":\"21.39014875\"},{\"1\":\"436\",\"2\":\"17.99363716\"},{\"1\":\"437\",\"2\":\"19.80622008\"},{\"1\":\"438\",\"2\":\"28.30116014\"},{\"1\":\"439\",\"2\":\"21.51915263\"},{\"1\":\"440\",\"2\":\"18.16048590\"},{\"1\":\"441\",\"2\":\"20.55970985\"},{\"1\":\"442\",\"2\":\"29.42974746\"},{\"1\":\"443\",\"2\":\"21.53584968\"},{\"1\":\"444\",\"2\":\"14.64190344\"},{\"1\":\"445\",\"2\":\"17.29999723\"},{\"1\":\"446\",\"2\":\"27.82951849\"},{\"1\":\"447\",\"2\":\"18.69110554\"},{\"1\":\"448\",\"2\":\"21.12538267\"},{\"1\":\"449\",\"2\":\"15.30695465\"},{\"1\":\"450\",\"2\":\"3.55855007\"},{\"1\":\"451\",\"2\":\"25.98504815\"},{\"1\":\"452\",\"2\":\"18.26334755\"},{\"1\":\"453\",\"2\":\"22.07158551\"},{\"1\":\"454\",\"2\":\"29.04561422\"},{\"1\":\"455\",\"2\":\"11.31640266\"},{\"1\":\"456\",\"2\":\"21.28965942\"},{\"1\":\"457\",\"2\":\"22.34975370\"},{\"1\":\"458\",\"2\":\"0.52093525\"},{\"1\":\"459\",\"2\":\"20.34933524\"},{\"1\":\"460\",\"2\":\"1.42289677\"},{\"1\":\"461\",\"2\":\"27.59932949\"},{\"1\":\"462\",\"2\":\"2.89372426\"},{\"1\":\"463\",\"2\":\"18.81056723\"},{\"1\":\"464\",\"2\":\"6.40705688\"},{\"1\":\"465\",\"2\":\"21.20666586\"},{\"1\":\"466\",\"2\":\"15.50679774\"},{\"1\":\"467\",\"2\":\"6.70022594\"},{\"1\":\"468\",\"2\":\"27.89876780\"},{\"1\":\"469\",\"2\":\"19.11103416\"},{\"1\":\"470\",\"2\":\"14.01322254\"},{\"1\":\"471\",\"2\":\"16.22470100\"},{\"1\":\"472\",\"2\":\"27.87636896\"},{\"1\":\"473\",\"2\":\"24.34938096\"},{\"1\":\"474\",\"2\":\"25.39768851\"},{\"1\":\"475\",\"2\":\"4.45197798\"},{\"1\":\"476\",\"2\":\"1.53750490\"},{\"1\":\"477\",\"2\":\"22.63620186\"},{\"1\":\"478\",\"2\":\"14.25112401\"},{\"1\":\"479\",\"2\":\"24.80635514\"},{\"1\":\"480\",\"2\":\"15.37004618\"},{\"1\":\"481\",\"2\":\"21.88684908\"},{\"1\":\"482\",\"2\":\"10.51672163\"},{\"1\":\"483\",\"2\":\"24.50996733\"},{\"1\":\"484\",\"2\":\"11.72664362\"},{\"1\":\"485\",\"2\":\"18.45670694\"},{\"1\":\"486\",\"2\":\"4.31498132\"},{\"1\":\"487\",\"2\":\"12.07116565\"},{\"1\":\"488\",\"2\":\"5.01115491\"},{\"1\":\"489\",\"2\":\"22.04236976\"},{\"1\":\"490\",\"2\":\"4.63524594\"},{\"1\":\"491\",\"2\":\"22.42581264\"},{\"1\":\"492\",\"2\":\"2.26363320\"},{\"1\":\"493\",\"2\":\"6.90867981\"},{\"1\":\"494\",\"2\":\"26.44155943\"},{\"1\":\"495\",\"2\":\"0.55509018\"},{\"1\":\"496\",\"2\":\"0.14361411\"},{\"1\":\"497\",\"2\":\"15.38088849\"},{\"1\":\"498\",\"2\":\"8.41076879\"},{\"1\":\"499\",\"2\":\"28.90797283\"},{\"1\":\"500\",\"2\":\"23.83094005\"},{\"1\":\"501\",\"2\":\"18.23616864\"},{\"1\":\"502\",\"2\":\"2.37112971\"},{\"1\":\"503\",\"2\":\"27.59622060\"},{\"1\":\"504\",\"2\":\"2.43101197\"},{\"1\":\"505\",\"2\":\"20.11683017\"},{\"1\":\"506\",\"2\":\"1.15869150\"},{\"1\":\"507\",\"2\":\"21.94247100\"},{\"1\":\"508\",\"2\":\"21.83020435\"},{\"1\":\"509\",\"2\":\"9.59816972\"},{\"1\":\"510\",\"2\":\"18.86794155\"},{\"1\":\"511\",\"2\":\"26.48611553\"},{\"1\":\"512\",\"2\":\"2.29030104\"},{\"1\":\"513\",\"2\":\"15.46201328\"},{\"1\":\"514\",\"2\":\"7.95034215\"},{\"1\":\"515\",\"2\":\"17.05755436\"},{\"1\":\"516\",\"2\":\"6.58767968\"},{\"1\":\"517\",\"2\":\"10.07531458\"},{\"1\":\"518\",\"2\":\"1.78737030\"},{\"1\":\"519\",\"2\":\"14.13113301\"},{\"1\":\"520\",\"2\":\"5.33891652\"},{\"1\":\"521\",\"2\":\"7.99536390\"},{\"1\":\"522\",\"2\":\"17.49613540\"},{\"1\":\"523\",\"2\":\"29.61214882\"},{\"1\":\"524\",\"2\":\"22.00217134\"},{\"1\":\"525\",\"2\":\"10.62230572\"},{\"1\":\"526\",\"2\":\"5.39191182\"},{\"1\":\"527\",\"2\":\"28.28376311\"},{\"1\":\"528\",\"2\":\"4.09335926\"},{\"1\":\"529\",\"2\":\"3.32336883\"},{\"1\":\"530\",\"2\":\"13.09906285\"},{\"1\":\"531\",\"2\":\"12.29163133\"},{\"1\":\"532\",\"2\":\"1.02804122\"},{\"1\":\"533\",\"2\":\"3.63867698\"},{\"1\":\"534\",\"2\":\"28.89265722\"},{\"1\":\"535\",\"2\":\"1.05562723\"},{\"1\":\"536\",\"2\":\"27.72558298\"},{\"1\":\"537\",\"2\":\"24.31650326\"},{\"1\":\"538\",\"2\":\"15.21048615\"},{\"1\":\"539\",\"2\":\"23.74477396\"},{\"1\":\"540\",\"2\":\"10.95966802\"},{\"1\":\"541\",\"2\":\"14.82571477\"},{\"1\":\"542\",\"2\":\"9.69711231\"},{\"1\":\"543\",\"2\":\"13.49656616\"},{\"1\":\"544\",\"2\":\"29.05379775\"},{\"1\":\"545\",\"2\":\"26.99015575\"},{\"1\":\"546\",\"2\":\"11.70335405\"},{\"1\":\"547\",\"2\":\"24.72241084\"},{\"1\":\"548\",\"2\":\"20.80310749\"},{\"1\":\"549\",\"2\":\"21.29865146\"},{\"1\":\"550\",\"2\":\"4.27487598\"},{\"1\":\"551\",\"2\":\"0.18877497\"},{\"1\":\"552\",\"2\":\"15.52615040\"},{\"1\":\"553\",\"2\":\"8.03915869\"},{\"1\":\"554\",\"2\":\"7.31296097\"},{\"1\":\"555\",\"2\":\"15.91223379\"},{\"1\":\"556\",\"2\":\"1.51910824\"},{\"1\":\"557\",\"2\":\"23.18906535\"},{\"1\":\"558\",\"2\":\"15.88347173\"},{\"1\":\"559\",\"2\":\"16.51760637\"},{\"1\":\"560\",\"2\":\"23.22923348\"},{\"1\":\"561\",\"2\":\"15.25847444\"},{\"1\":\"562\",\"2\":\"25.09333366\"},{\"1\":\"563\",\"2\":\"13.93844577\"},{\"1\":\"564\",\"2\":\"15.25182184\"},{\"1\":\"565\",\"2\":\"18.29192387\"},{\"1\":\"566\",\"2\":\"16.18723450\"},{\"1\":\"567\",\"2\":\"15.78160366\"},{\"1\":\"568\",\"2\":\"18.97948554\"},{\"1\":\"569\",\"2\":\"27.56204371\"},{\"1\":\"570\",\"2\":\"6.90978096\"},{\"1\":\"571\",\"2\":\"2.81436247\"},{\"1\":\"572\",\"2\":\"22.30922569\"},{\"1\":\"573\",\"2\":\"4.22921974\"},{\"1\":\"574\",\"2\":\"25.49643823\"},{\"1\":\"575\",\"2\":\"25.86424883\"},{\"1\":\"576\",\"2\":\"15.46743162\"},{\"1\":\"577\",\"2\":\"9.50067313\"},{\"1\":\"578\",\"2\":\"28.23881332\"},{\"1\":\"579\",\"2\":\"17.41533428\"},{\"1\":\"580\",\"2\":\"26.07017294\"},{\"1\":\"581\",\"2\":\"11.27339201\"},{\"1\":\"582\",\"2\":\"0.44793117\"},{\"1\":\"583\",\"2\":\"17.17957113\"},{\"1\":\"584\",\"2\":\"0.57937812\"},{\"1\":\"585\",\"2\":\"4.70337945\"},{\"1\":\"586\",\"2\":\"15.36253812\"},{\"1\":\"587\",\"2\":\"24.09799757\"},{\"1\":\"588\",\"2\":\"9.98313663\"},{\"1\":\"589\",\"2\":\"24.29376919\"},{\"1\":\"590\",\"2\":\"20.03532447\"},{\"1\":\"591\",\"2\":\"16.86236385\"},{\"1\":\"592\",\"2\":\"28.49393641\"},{\"1\":\"593\",\"2\":\"24.80527276\"},{\"1\":\"594\",\"2\":\"10.29042019\"},{\"1\":\"595\",\"2\":\"17.28378473\"},{\"1\":\"596\",\"2\":\"4.29394705\"},{\"1\":\"597\",\"2\":\"4.13894035\"},{\"1\":\"598\",\"2\":\"27.10331543\"},{\"1\":\"599\",\"2\":\"19.01784361\"},{\"1\":\"600\",\"2\":\"4.13087844\"},{\"1\":\"601\",\"2\":\"7.61913192\"},{\"1\":\"602\",\"2\":\"0.22471917\"},{\"1\":\"603\",\"2\":\"7.58358095\"},{\"1\":\"604\",\"2\":\"0.70820356\"},{\"1\":\"605\",\"2\":\"26.15456688\"},{\"1\":\"606\",\"2\":\"25.00787396\"},{\"1\":\"607\",\"2\":\"12.13710360\"},{\"1\":\"608\",\"2\":\"29.51772553\"},{\"1\":\"609\",\"2\":\"23.29129434\"},{\"1\":\"610\",\"2\":\"0.79500558\"},{\"1\":\"611\",\"2\":\"8.64801754\"},{\"1\":\"612\",\"2\":\"8.92626902\"},{\"1\":\"613\",\"2\":\"3.55413855\"},{\"1\":\"614\",\"2\":\"20.95414013\"},{\"1\":\"615\",\"2\":\"13.97414454\"},{\"1\":\"616\",\"2\":\"12.05990767\"},{\"1\":\"617\",\"2\":\"25.30801366\"},{\"1\":\"618\",\"2\":\"21.94305107\"},{\"1\":\"619\",\"2\":\"27.24628801\"},{\"1\":\"620\",\"2\":\"26.99409339\"},{\"1\":\"621\",\"2\":\"21.48838394\"},{\"1\":\"622\",\"2\":\"25.64111639\"},{\"1\":\"623\",\"2\":\"16.02956112\"},{\"1\":\"624\",\"2\":\"24.97976664\"},{\"1\":\"625\",\"2\":\"19.43177693\"},{\"1\":\"626\",\"2\":\"4.07977849\"},{\"1\":\"627\",\"2\":\"22.07207988\"},{\"1\":\"628\",\"2\":\"18.20536372\"},{\"1\":\"629\",\"2\":\"8.25589764\"},{\"1\":\"630\",\"2\":\"25.94543448\"},{\"1\":\"631\",\"2\":\"26.68614750\"},{\"1\":\"632\",\"2\":\"13.17340614\"},{\"1\":\"633\",\"2\":\"4.13971917\"},{\"1\":\"634\",\"2\":\"18.69442663\"},{\"1\":\"635\",\"2\":\"21.15617341\"},{\"1\":\"636\",\"2\":\"26.62828154\"},{\"1\":\"637\",\"2\":\"1.58231570\"},{\"1\":\"638\",\"2\":\"6.39004376\"},{\"1\":\"639\",\"2\":\"1.36808490\"},{\"1\":\"640\",\"2\":\"7.59057867\"},{\"1\":\"641\",\"2\":\"12.24693146\"},{\"1\":\"642\",\"2\":\"5.26981595\"},{\"1\":\"643\",\"2\":\"5.19349064\"},{\"1\":\"644\",\"2\":\"16.23022058\"},{\"1\":\"645\",\"2\":\"19.43334169\"},{\"1\":\"646\",\"2\":\"8.32330740\"},{\"1\":\"647\",\"2\":\"21.81385769\"},{\"1\":\"648\",\"2\":\"26.36377704\"},{\"1\":\"649\",\"2\":\"16.52527308\"},{\"1\":\"650\",\"2\":\"21.36186962\"},{\"1\":\"651\",\"2\":\"21.76063207\"},{\"1\":\"652\",\"2\":\"9.43167117\"},{\"1\":\"653\",\"2\":\"28.81018798\"},{\"1\":\"654\",\"2\":\"1.97403420\"},{\"1\":\"655\",\"2\":\"20.11645230\"},{\"1\":\"656\",\"2\":\"20.45099184\"},{\"1\":\"657\",\"2\":\"8.20116245\"},{\"1\":\"658\",\"2\":\"7.61681224\"},{\"1\":\"659\",\"2\":\"22.39749865\"},{\"1\":\"660\",\"2\":\"20.45608649\"},{\"1\":\"661\",\"2\":\"23.24401018\"},{\"1\":\"662\",\"2\":\"16.03424410\"},{\"1\":\"663\",\"2\":\"24.69163685\"},{\"1\":\"664\",\"2\":\"7.58833783\"},{\"1\":\"665\",\"2\":\"19.79045543\"},{\"1\":\"666\",\"2\":\"4.83634152\"},{\"1\":\"667\",\"2\":\"22.71104205\"},{\"1\":\"668\",\"2\":\"22.46168953\"},{\"1\":\"669\",\"2\":\"21.28329621\"},{\"1\":\"670\",\"2\":\"14.84826955\"},{\"1\":\"671\",\"2\":\"17.71113721\"},{\"1\":\"672\",\"2\":\"24.99863414\"},{\"1\":\"673\",\"2\":\"1.11363730\"},{\"1\":\"674\",\"2\":\"5.18335772\"},{\"1\":\"675\",\"2\":\"17.93925157\"},{\"1\":\"676\",\"2\":\"15.98093777\"},{\"1\":\"677\",\"2\":\"9.71065524\"},{\"1\":\"678\",\"2\":\"28.08909436\"},{\"1\":\"679\",\"2\":\"12.12228267\"},{\"1\":\"680\",\"2\":\"21.41512543\"},{\"1\":\"681\",\"2\":\"27.59098297\"},{\"1\":\"682\",\"2\":\"10.43861453\"},{\"1\":\"683\",\"2\":\"17.17619657\"},{\"1\":\"684\",\"2\":\"15.64023849\"},{\"1\":\"685\",\"2\":\"7.81212623\"},{\"1\":\"686\",\"2\":\"7.94228212\"},{\"1\":\"687\",\"2\":\"27.67277035\"},{\"1\":\"688\",\"2\":\"11.51521985\"},{\"1\":\"689\",\"2\":\"7.23150658\"},{\"1\":\"690\",\"2\":\"3.21479284\"},{\"1\":\"691\",\"2\":\"19.54473338\"},{\"1\":\"692\",\"2\":\"15.11418222\"},{\"1\":\"693\",\"2\":\"29.11112360\"},{\"1\":\"694\",\"2\":\"18.85301092\"},{\"1\":\"695\",\"2\":\"24.07615190\"},{\"1\":\"696\",\"2\":\"4.43075927\"},{\"1\":\"697\",\"2\":\"8.07530223\"},{\"1\":\"698\",\"2\":\"7.10870020\"},{\"1\":\"699\",\"2\":\"16.42089552\"},{\"1\":\"700\",\"2\":\"5.14947769\"},{\"1\":\"701\",\"2\":\"26.45798509\"},{\"1\":\"702\",\"2\":\"15.92709096\"},{\"1\":\"703\",\"2\":\"22.54949688\"},{\"1\":\"704\",\"2\":\"23.11841410\"},{\"1\":\"705\",\"2\":\"23.20727685\"},{\"1\":\"706\",\"2\":\"24.02396576\"},{\"1\":\"707\",\"2\":\"28.11650863\"},{\"1\":\"708\",\"2\":\"23.53483649\"},{\"1\":\"709\",\"2\":\"10.83651507\"},{\"1\":\"710\",\"2\":\"14.52483727\"},{\"1\":\"711\",\"2\":\"19.27092228\"},{\"1\":\"712\",\"2\":\"4.96947936\"},{\"1\":\"713\",\"2\":\"6.37777295\"},{\"1\":\"714\",\"2\":\"19.66820788\"},{\"1\":\"715\",\"2\":\"10.33001991\"},{\"1\":\"716\",\"2\":\"2.76706099\"},{\"1\":\"717\",\"2\":\"2.65794648\"},{\"1\":\"718\",\"2\":\"13.18265599\"},{\"1\":\"719\",\"2\":\"15.87154296\"},{\"1\":\"720\",\"2\":\"26.15205297\"},{\"1\":\"721\",\"2\":\"3.47143965\"},{\"1\":\"722\",\"2\":\"5.68069562\"},{\"1\":\"723\",\"2\":\"21.81475559\"},{\"1\":\"724\",\"2\":\"18.99552750\"},{\"1\":\"725\",\"2\":\"4.07545613\"},{\"1\":\"726\",\"2\":\"22.48334356\"},{\"1\":\"727\",\"2\":\"25.15314901\"},{\"1\":\"728\",\"2\":\"4.14790113\"},{\"1\":\"729\",\"2\":\"26.80710363\"},{\"1\":\"730\",\"2\":\"12.71870700\"},{\"1\":\"731\",\"2\":\"0.23671982\"},{\"1\":\"732\",\"2\":\"18.27752029\"},{\"1\":\"733\",\"2\":\"20.38129024\"},{\"1\":\"734\",\"2\":\"25.49995270\"},{\"1\":\"735\",\"2\":\"19.34074980\"},{\"1\":\"736\",\"2\":\"27.88514764\"},{\"1\":\"737\",\"2\":\"23.62582308\"},{\"1\":\"738\",\"2\":\"4.57260252\"},{\"1\":\"739\",\"2\":\"4.84854108\"},{\"1\":\"740\",\"2\":\"13.21212999\"},{\"1\":\"741\",\"2\":\"27.19329578\"},{\"1\":\"742\",\"2\":\"1.45556869\"},{\"1\":\"743\",\"2\":\"24.08456709\"},{\"1\":\"744\",\"2\":\"16.55591665\"},{\"1\":\"745\",\"2\":\"10.49539158\"},{\"1\":\"746\",\"2\":\"2.12426508\"},{\"1\":\"747\",\"2\":\"3.30015942\"},{\"1\":\"748\",\"2\":\"27.21315860\"},{\"1\":\"749\",\"2\":\"13.60083407\"},{\"1\":\"750\",\"2\":\"6.42074840\"},{\"1\":\"751\",\"2\":\"15.80302568\"},{\"1\":\"752\",\"2\":\"7.64344939\"},{\"1\":\"753\",\"2\":\"3.61414381\"},{\"1\":\"754\",\"2\":\"3.44661766\"},{\"1\":\"755\",\"2\":\"4.44318358\"},{\"1\":\"756\",\"2\":\"2.85897752\"},{\"1\":\"757\",\"2\":\"18.31471199\"},{\"1\":\"758\",\"2\":\"9.24812254\"},{\"1\":\"759\",\"2\":\"15.63217551\"},{\"1\":\"760\",\"2\":\"6.64337234\"},{\"1\":\"761\",\"2\":\"25.32337808\"},{\"1\":\"762\",\"2\":\"10.41814572\"},{\"1\":\"763\",\"2\":\"19.13094874\"},{\"1\":\"764\",\"2\":\"22.86960758\"},{\"1\":\"765\",\"2\":\"22.85894301\"},{\"1\":\"766\",\"2\":\"5.86332334\"},{\"1\":\"767\",\"2\":\"0.05504268\"},{\"1\":\"768\",\"2\":\"27.66123282\"},{\"1\":\"769\",\"2\":\"25.70949992\"},{\"1\":\"770\",\"2\":\"29.95611676\"},{\"1\":\"771\",\"2\":\"15.84321597\"},{\"1\":\"772\",\"2\":\"10.35282277\"},{\"1\":\"773\",\"2\":\"12.69412339\"},{\"1\":\"774\",\"2\":\"3.80673125\"},{\"1\":\"775\",\"2\":\"6.16406827\"},{\"1\":\"776\",\"2\":\"2.99790168\"},{\"1\":\"777\",\"2\":\"24.26350489\"},{\"1\":\"778\",\"2\":\"16.80755850\"},{\"1\":\"779\",\"2\":\"13.83899124\"},{\"1\":\"780\",\"2\":\"10.87304362\"},{\"1\":\"781\",\"2\":\"10.24308386\"},{\"1\":\"782\",\"2\":\"10.72382789\"},{\"1\":\"783\",\"2\":\"9.30063335\"},{\"1\":\"784\",\"2\":\"10.87484150\"},{\"1\":\"785\",\"2\":\"10.25127639\"},{\"1\":\"786\",\"2\":\"19.50456381\"},{\"1\":\"787\",\"2\":\"1.03514625\"},{\"1\":\"788\",\"2\":\"24.25549979\"},{\"1\":\"789\",\"2\":\"13.27121684\"},{\"1\":\"790\",\"2\":\"25.87039498\"},{\"1\":\"791\",\"2\":\"11.24287691\"},{\"1\":\"792\",\"2\":\"15.81979402\"},{\"1\":\"793\",\"2\":\"3.38889360\"},{\"1\":\"794\",\"2\":\"7.21797730\"},{\"1\":\"795\",\"2\":\"21.59932912\"},{\"1\":\"796\",\"2\":\"1.33471450\"},{\"1\":\"797\",\"2\":\"17.68906805\"},{\"1\":\"798\",\"2\":\"0.33489309\"},{\"1\":\"799\",\"2\":\"13.29441077\"},{\"1\":\"800\",\"2\":\"25.58799972\"},{\"1\":\"801\",\"2\":\"8.34362524\"},{\"1\":\"802\",\"2\":\"5.24244705\"},{\"1\":\"803\",\"2\":\"29.86772894\"},{\"1\":\"804\",\"2\":\"11.27868217\"},{\"1\":\"805\",\"2\":\"1.77041067\"},{\"1\":\"806\",\"2\":\"12.26556163\"},{\"1\":\"807\",\"2\":\"4.08045416\"},{\"1\":\"808\",\"2\":\"9.23194574\"},{\"1\":\"809\",\"2\":\"12.71412474\"},{\"1\":\"810\",\"2\":\"21.38715362\"},{\"1\":\"811\",\"2\":\"12.41157442\"},{\"1\":\"812\",\"2\":\"3.27262945\"},{\"1\":\"813\",\"2\":\"17.68681702\"},{\"1\":\"814\",\"2\":\"21.29433260\"},{\"1\":\"815\",\"2\":\"12.17109138\"},{\"1\":\"816\",\"2\":\"10.58917779\"},{\"1\":\"817\",\"2\":\"16.98192174\"},{\"1\":\"818\",\"2\":\"2.54616702\"},{\"1\":\"819\",\"2\":\"25.22683462\"},{\"1\":\"820\",\"2\":\"16.03544157\"},{\"1\":\"821\",\"2\":\"15.04064024\"},{\"1\":\"822\",\"2\":\"3.77273770\"},{\"1\":\"823\",\"2\":\"18.32934281\"},{\"1\":\"824\",\"2\":\"5.93192280\"},{\"1\":\"825\",\"2\":\"10.68586400\"},{\"1\":\"826\",\"2\":\"2.71822324\"},{\"1\":\"827\",\"2\":\"14.42678049\"},{\"1\":\"828\",\"2\":\"11.41946887\"},{\"1\":\"829\",\"2\":\"3.00407069\"},{\"1\":\"830\",\"2\":\"10.19740361\"},{\"1\":\"831\",\"2\":\"21.18003317\"},{\"1\":\"832\",\"2\":\"26.14440167\"},{\"1\":\"833\",\"2\":\"17.06804041\"},{\"1\":\"834\",\"2\":\"23.59274075\"},{\"1\":\"835\",\"2\":\"11.64061781\"},{\"1\":\"836\",\"2\":\"2.32737881\"},{\"1\":\"837\",\"2\":\"20.44001259\"},{\"1\":\"838\",\"2\":\"4.76478560\"},{\"1\":\"839\",\"2\":\"24.71379337\"},{\"1\":\"840\",\"2\":\"24.77519453\"},{\"1\":\"841\",\"2\":\"17.99014271\"},{\"1\":\"842\",\"2\":\"5.75588196\"},{\"1\":\"843\",\"2\":\"2.16911993\"},{\"1\":\"844\",\"2\":\"1.22090104\"},{\"1\":\"845\",\"2\":\"3.82330611\"},{\"1\":\"846\",\"2\":\"20.15392916\"},{\"1\":\"847\",\"2\":\"9.60326056\"},{\"1\":\"848\",\"2\":\"5.16540379\"},{\"1\":\"849\",\"2\":\"12.45379922\"},{\"1\":\"850\",\"2\":\"13.28796059\"},{\"1\":\"851\",\"2\":\"11.86287006\"},{\"1\":\"852\",\"2\":\"20.29859643\"},{\"1\":\"853\",\"2\":\"13.84376860\"},{\"1\":\"854\",\"2\":\"4.95336537\"},{\"1\":\"855\",\"2\":\"9.14834554\"},{\"1\":\"856\",\"2\":\"6.23437267\"},{\"1\":\"857\",\"2\":\"12.74852165\"},{\"1\":\"858\",\"2\":\"18.42469239\"},{\"1\":\"859\",\"2\":\"2.50559419\"},{\"1\":\"860\",\"2\":\"4.44630169\"},{\"1\":\"861\",\"2\":\"27.09661371\"},{\"1\":\"862\",\"2\":\"21.36234795\"},{\"1\":\"863\",\"2\":\"3.00574969\"},{\"1\":\"864\",\"2\":\"0.83713321\"},{\"1\":\"865\",\"2\":\"25.36174874\"},{\"1\":\"866\",\"2\":\"28.87985375\"},{\"1\":\"867\",\"2\":\"13.74831506\"},{\"1\":\"868\",\"2\":\"25.35327182\"},{\"1\":\"869\",\"2\":\"12.70325953\"},{\"1\":\"870\",\"2\":\"5.17307359\"},{\"1\":\"871\",\"2\":\"13.63094065\"},{\"1\":\"872\",\"2\":\"14.55916693\"},{\"1\":\"873\",\"2\":\"6.27789009\"},{\"1\":\"874\",\"2\":\"2.80767876\"},{\"1\":\"875\",\"2\":\"22.85234640\"},{\"1\":\"876\",\"2\":\"19.30655676\"},{\"1\":\"877\",\"2\":\"0.27821728\"},{\"1\":\"878\",\"2\":\"16.68406505\"},{\"1\":\"879\",\"2\":\"6.40513663\"},{\"1\":\"880\",\"2\":\"7.72135927\"},{\"1\":\"881\",\"2\":\"0.79103180\"},{\"1\":\"882\",\"2\":\"27.04417687\"},{\"1\":\"883\",\"2\":\"1.79142114\"},{\"1\":\"884\",\"2\":\"5.56745985\"},{\"1\":\"885\",\"2\":\"2.18831601\"},{\"1\":\"886\",\"2\":\"2.21925403\"},{\"1\":\"887\",\"2\":\"17.70047102\"},{\"1\":\"888\",\"2\":\"6.21666149\"},{\"1\":\"889\",\"2\":\"1.36030485\"},{\"1\":\"890\",\"2\":\"21.21758044\"},{\"1\":\"891\",\"2\":\"23.19494686\"},{\"1\":\"892\",\"2\":\"14.47518775\"},{\"1\":\"893\",\"2\":\"8.84783751\"},{\"1\":\"894\",\"2\":\"5.32492983\"},{\"1\":\"895\",\"2\":\"22.48245830\"},{\"1\":\"896\",\"2\":\"19.28372380\"},{\"1\":\"897\",\"2\":\"27.48034459\"},{\"1\":\"898\",\"2\":\"24.70487057\"},{\"1\":\"899\",\"2\":\"8.00545029\"},{\"1\":\"900\",\"2\":\"8.45565304\"},{\"1\":\"901\",\"2\":\"7.80314541\"},{\"1\":\"902\",\"2\":\"25.80687525\"},{\"1\":\"903\",\"2\":\"28.20051021\"},{\"1\":\"904\",\"2\":\"13.05773278\"},{\"1\":\"905\",\"2\":\"19.17772947\"},{\"1\":\"906\",\"2\":\"29.72308018\"},{\"1\":\"907\",\"2\":\"20.27046272\"},{\"1\":\"908\",\"2\":\"17.97622324\"},{\"1\":\"909\",\"2\":\"21.67749231\"},{\"1\":\"910\",\"2\":\"1.12684628\"},{\"1\":\"911\",\"2\":\"22.94989524\"},{\"1\":\"912\",\"2\":\"24.13175539\"},{\"1\":\"913\",\"2\":\"28.41362476\"},{\"1\":\"914\",\"2\":\"25.11089469\"},{\"1\":\"915\",\"2\":\"0.67646472\"},{\"1\":\"916\",\"2\":\"16.55111630\"},{\"1\":\"917\",\"2\":\"15.80507174\"},{\"1\":\"918\",\"2\":\"21.53329839\"},{\"1\":\"919\",\"2\":\"27.35162175\"},{\"1\":\"920\",\"2\":\"4.24038327\"},{\"1\":\"921\",\"2\":\"15.61486362\"},{\"1\":\"922\",\"2\":\"11.89807023\"},{\"1\":\"923\",\"2\":\"21.03012824\"},{\"1\":\"924\",\"2\":\"8.61335917\"},{\"1\":\"925\",\"2\":\"2.95336662\"},{\"1\":\"926\",\"2\":\"22.10096980\"},{\"1\":\"927\",\"2\":\"21.42984963\"},{\"1\":\"928\",\"2\":\"26.57457779\"},{\"1\":\"929\",\"2\":\"0.32530567\"},{\"1\":\"930\",\"2\":\"11.67946577\"},{\"1\":\"931\",\"2\":\"24.84896766\"},{\"1\":\"932\",\"2\":\"28.30590534\"},{\"1\":\"933\",\"2\":\"19.27874641\"},{\"1\":\"934\",\"2\":\"22.59183099\"},{\"1\":\"935\",\"2\":\"5.54906694\"},{\"1\":\"936\",\"2\":\"15.92738783\"},{\"1\":\"937\",\"2\":\"23.82532625\"},{\"1\":\"938\",\"2\":\"27.78281898\"},{\"1\":\"939\",\"2\":\"11.12884755\"},{\"1\":\"940\",\"2\":\"17.37371000\"},{\"1\":\"941\",\"2\":\"2.08964465\"},{\"1\":\"942\",\"2\":\"14.29634497\"},{\"1\":\"943\",\"2\":\"17.93836294\"},{\"1\":\"944\",\"2\":\"0.02836663\"},{\"1\":\"945\",\"2\":\"23.52984892\"},{\"1\":\"946\",\"2\":\"12.08360466\"},{\"1\":\"947\",\"2\":\"4.83382977\"},{\"1\":\"948\",\"2\":\"22.58295289\"},{\"1\":\"949\",\"2\":\"24.41841301\"},{\"1\":\"950\",\"2\":\"4.35457614\"},{\"1\":\"951\",\"2\":\"18.55395347\"},{\"1\":\"952\",\"2\":\"9.81627590\"},{\"1\":\"953\",\"2\":\"12.85618000\"},{\"1\":\"954\",\"2\":\"3.75257013\"},{\"1\":\"955\",\"2\":\"14.58650635\"},{\"1\":\"956\",\"2\":\"28.88595521\"},{\"1\":\"957\",\"2\":\"12.81251761\"},{\"1\":\"958\",\"2\":\"17.77156874\"},{\"1\":\"959\",\"2\":\"2.36495243\"},{\"1\":\"960\",\"2\":\"10.50472292\"},{\"1\":\"961\",\"2\":\"10.88613254\"},{\"1\":\"962\",\"2\":\"18.03848800\"},{\"1\":\"963\",\"2\":\"6.85033504\"},{\"1\":\"964\",\"2\":\"29.35935741\"},{\"1\":\"965\",\"2\":\"14.77169513\"},{\"1\":\"966\",\"2\":\"15.44966381\"},{\"1\":\"967\",\"2\":\"11.82772621\"},{\"1\":\"968\",\"2\":\"28.18201558\"},{\"1\":\"969\",\"2\":\"28.28515080\"},{\"1\":\"970\",\"2\":\"25.84118795\"},{\"1\":\"971\",\"2\":\"2.32863119\"},{\"1\":\"972\",\"2\":\"6.74184497\"},{\"1\":\"973\",\"2\":\"15.22274302\"},{\"1\":\"974\",\"2\":\"13.61504895\"},{\"1\":\"975\",\"2\":\"26.69289316\"},{\"1\":\"976\",\"2\":\"2.79583029\"},{\"1\":\"977\",\"2\":\"20.07001006\"},{\"1\":\"978\",\"2\":\"28.03155079\"},{\"1\":\"979\",\"2\":\"5.06785383\"},{\"1\":\"980\",\"2\":\"2.62971973\"},{\"1\":\"981\",\"2\":\"28.59565169\"},{\"1\":\"982\",\"2\":\"11.50206714\"},{\"1\":\"983\",\"2\":\"11.71660302\"},{\"1\":\"984\",\"2\":\"15.06892989\"},{\"1\":\"985\",\"2\":\"15.64412930\"},{\"1\":\"986\",\"2\":\"23.11437869\"},{\"1\":\"987\",\"2\":\"12.91659115\"},{\"1\":\"988\",\"2\":\"21.31045686\"},{\"1\":\"989\",\"2\":\"8.83304000\"},{\"1\":\"990\",\"2\":\"28.03850106\"},{\"1\":\"991\",\"2\":\"24.60741165\"},{\"1\":\"992\",\"2\":\"1.44645144\"},{\"1\":\"993\",\"2\":\"26.57894109\"},{\"1\":\"994\",\"2\":\"29.12689109\"},{\"1\":\"995\",\"2\":\"23.14159813\"},{\"1\":\"996\",\"2\":\"24.09883305\"},{\"1\":\"997\",\"2\":\"26.35455905\"},{\"1\":\"998\",\"2\":\"9.82991366\"},{\"1\":\"999\",\"2\":\"20.18595314\"},{\"1\":\"1000\",\"2\":\"22.39149915\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n* 3. Create a histogram of the simulated wait times with 30 bins.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Set random seed to 334\nset.seed(334)\n\n# 3. Generate 1000 wait times between 0 and 30 mins, save in time column\nwait_times %>%\n  mutate(time = runif(1000, min = 0, max = 30)) %>%\n  # Create a histogram of simulated times\n  ggplot(aes(time)) +\n  geom_histogram()\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-31-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nSuperb simulating! Unless Amir figures out exactly what time each backup happens, he won't be able to time his data entry so it gets backed up sooner, but it looks like he'll wait about 15 minutes on average.\n\n## The binomial distribution\n\nTheory. Coming soon ...\n\n\n**1. The binomial distribution**\n\nIt's time to further expand your toolbox of distributions. In this video, you'll learn about the binomial distribution.\n\n**2. Coin flipping**\n\nWe'll start by flipping a coin, which has two possible outcomes, heads or tails, each with a probability of 50%.\n\n**3. Binary outcomes**\n\nThis is just one example of a binary outcome, or an outcome with two possible values. We could also represent these outcomes as a 1 and a 0, a success or a failure, and a win or a loss.\n\n**4. A single flip**\n\nIn R, we can simulate this using the rbinom function, which takes in the number of trials, or times we want to flip, the number of coins we want to flip, and the probability of heads or success. This will return a 1, which we'll count as a head, or a 0, which we'll count as tails.We can use rbinom 1, 1, 0-point-5 to flip 1 coin 1 time with a 50% probability of heads.\n\n**5. One flip many times**\n\nTo perform eight coin flips, we can change the first argument to an 8, which will give us eight flips of 1 coin with a 50% chance of heads.This gives us a set of 8 ones and zeros.\n\n**6. Many flips one time**\n\nIf we swap the first two arguments, we simulate one flip of eight coins. This gives us one number, which is the total number of heads or successes.\n\n**7. Many flips many times**\n\nSimilarly, we can pass 10 and 3 into rbinom to simulate 10 flips of 3 coins. This returns 10 numbers, each representing the total number of heads from each set of flips.\n\n**8. Other probabilities**\n\nWe could also have a coin that's heavier on one side than the other, so the probability of getting heads is only 25%. To simulate flips with this coin, we'll adjust the third argument of rbinom to 0-point-25. The result has lower numbers, since getting multiple heads isn't as likely with the new coin.\n\n**9. Binomial distribution**\n\nThe binomial distribution describes the probability of the number of successes in a sequence of independent trials. In other words, it can tell us the probability of getting some number of heads in a sequence of coin flips. Note that this is a discrete distribution since we're working with a countable outcome.The binomial distribution can be described using two parameters, n and p. n represents the total number of trials being performed. n and p are also the second and third arguments of rbinom.Here's what the distribution looks like for 10 coins. We have the biggest chance of getting 5 heads total, and a much smaller chance of getting 0 heads or 10 heads.\n\n**10. What's the probability of 7 heads?**\n\nTo get the probability of getting 7 heads out of 10 coins, we can use dbinom. The first argument is the number of heads or successes. The second argument is the number of trials, n, and the third is the probability of success, p.If we flip 10 coins, there's about a 12% chance that 7 of them will be heads.\n\n**11. What's the probability of 7 or fewer heads?**\n\npbinom gives the probability of getting a number of successes less than or equal to the first argument. The probability of getting 7 or fewer heads out of 10 coins is about 95%.\n\n**12. What's the probability of more than 7 heads?**\n\nWe can use the lower-dot-tail argument to get the probability of a number of successes greater than the first argument. Note that this is the same as 1 minus the same pbinom call from the previous slide.\n\n**13. Expected value**\n\nThe expected value of the binomial distribution can be calculated by multiplying n times p. The expected number of heads we'll get from flipping 10 coins is 10 times 0-point-5, which is 5.\n\n**14. Independence**\n\nIt's important to remember that in order for the binomial distribution to apply, each trial must be independent, so the outcome of one trial shouldn't have an effect on the next.For example, if we're picking randomly from these cards with zeros and ones, we have a 50-50 chance of getting a 0 or a 1.\n\n**15. Independence**\n\nBut since we're sampling without replacement, the probabilities for the second trial are different due to the outcome of the first trial. Since these trials aren't independent, we can't calculate accurate probabilities for this situation using the binomial distribution.\n\n**16. Let's practice!**\n\nTime to explore binary outcomes using the binomial distribution.\n\n## Simulating sales deals\n\nAssume that Amir usually works on 3 deals per week, and overall, he wins 30% of deals he works on. Each deal has a binary outcome: it's either lost, or won, so you can model his sales deals with a binomial distribution. In this exercise, you'll help Amir simulate a year's worth of his deals so he can better understand his performance.\n\n**Steps**\n\n1. Set the random seed to 10 and simulate a single deal.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Set random seed to 10\nset.seed(10)\n\n# 1. Simulate a single deal\nrbinom(1, 1, 0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0\n```\n:::\n:::\n\n\n2. Simulate a typical week of Amir's deals, or one week of 3 deals.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Set random seed to 10\nset.seed(10)\n\n# 2. Simulate a single deal\nrbinom(1, 3, 0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1\n```\n:::\n:::\n\n\n3. Simulate a year's worth of Amir's deals, or 52 weeks of 3 deals each, and store in `deals`.\n4. Calculate the mean number of deals he won per week.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set random seed to 10\nset.seed(10)\n\n# Simulate 52 weeks of 3 deals\ndeals <- rbinom(52,3,0.3)\n\n# Calculate mean deals won per week\nmean(deals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.8076923\n```\n:::\n:::\n\n\nBrilliant binomial simulation! In this simulated year, Amir won 0.8 deals on average each week.\n\n## Calculating binomial probabilities\n\nJust as in the last exercise, assume that Amir wins 30% of deals. He wants to get an idea of how likely he is to close a certain number of deals each week. In this exercise, you'll calculate what the chances are of him closing different numbers of deals using the binomial distribution.\n\n\n**Steps**\n\n1. What's the probability that Amir closes all 3 deals in a week?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of closing 3 out of 3 deals\ndbinom(3,3,0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.027\n```\n:::\n:::\n\n\n2. What's the probability that Amir closes 1 or fewer deals in a week?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of closing <= 1 deal out of 3 deals\npbinom(1,3,0.3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.784\n```\n:::\n:::\n\n\n3. What's the probability that Amir closes more than 1 deal?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of closing > 1 deal out of 3 deals\npbinom(1,3,0.3,lower.tail=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.216\n```\n:::\n:::\n\n\n\nPowerful probability calculations! Amir has about a 22% chance of closing more than one deal in a week.\n\n## How many sales will be won?\n\nNow Amir wants to know how many deals he can expect to close each week if his win rate changes. Luckily, you can use your binomial distribution knowledge to help him calculate the expected value in different situations. Recall from the video that the expected value of a binomial distribution can be calculated by (n * p).\n\n**Steps**\n\n1. Calculate the expected number of sales out of the **3** he works on that Amir will win each week if he maintains his 30% win rate.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Expected number won with 30% win rate\nwon_30pct <- 3 * 0.30\nwon_30pct\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.9\n```\n:::\n:::\n\n\n2. Calculate the expected number of sales out of the 3 he works on that he'll win if his win rate drops to 25%.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Expected number won with 25% win rate\nwon_25pct <- 3 * 0.25\nwon_25pct\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.75\n```\n:::\n:::\n\n\n3. Calculate the expected number of sales out of the 3 he works on that he'll win if his win rate rises to 35%.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Expected number won with 35% win rate\nwon_35pct <- 3 * 0.35\nwon_35pct\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 1.05\n```\n:::\n:::\n\n\nExcellent expectation experimentation! If Amir's win rate goes up by 5%, he can expect to close more than 1 deal on average each week.\n\n# 3. More Distributions and the Central Limit Theorem\n\nIt’s time to explore one of the most important probability distributions in statistics, normal distribution. You’ll create histograms to plot normal distributions and gain an understanding of the central limit theorem, before expanding your knowledge of statistical functions by adding the Poisson, exponential, and t-distributions to your repertoire.\n\n## The normal distribution\n\nTheory. Coming soon ...\n\n\n**1. The normal distribution**\n\nThe next probability distribution we'll discuss is the normal distribution. It's one of the most important probability distributions you'll learn about since a countless number of statistical methods rely on it, and it applies to more real-world situations than the distributions we've covered so far.\n\n**2. What is the normal distribution?**\n\nThe normal distribution looks like this. Its shape is commonly referred to as a \"bell curve\". The normal distribution has a few important properties.\n\n**3. Symmetrical**\n\nFirst, it's symmetrical, so the left side is a mirror image of the right.\n\n**4. Area = 1**\n\nSecond, just like any continuous distribution, the area beneath the curve is 1.\n\n**5. Curve never hits 0**\n\nThird, the probability never hits 0, even if it looks like it at the tail ends. Only 0-point-006% of its area is contained beyond the edges of this graph.\n\n**6. Described by mean and standard deviation**\n\nThe normal distribution is described by its mean and standard deviation. Here is a normal distribution with a mean of 20 and standard deviation of 3, and here is a normal distribution with a mean of 0 and a standard deviation of 1. When a normal distribution has mean 0 and a standard deviation of 1, it's a special distribution called the standard normal distributionNotice how both distributions have the same shape,\n\n**7. Described by mean and standard deviation**\n\nbut their axes have different scales.\n\n**8. Areas under the normal distribution**\n\nFor the normal distribution, 68% of the area is within 1 standard deviation of the mean.\n\n**9. Areas under the normal distribution**\n\n95% of the area falls within 2 standard deviations of the mean,\n\n**10. Areas under the normal distribution**\n\nand 99-point-7% of the area falls within three standard deviations. This is sometimes called the 68-95-99-point-7 rule.\n\n**11. Lots of histograms look normal**\n\nThere's lots of real-world data shaped like the normal distribution. For example, here is a histogram of the heights of women that participated in the National Health and Nutrition Examination Survey. The mean height is around 161 centimeters and the standard deviation is about 7 centimeters.\n\n**12. Approximating data with the normal distribution**\n\nSince this height data closely resembles the normal distribution, we can take the area under a normal distribution with mean 161 and standard deviation 7 to approximate what percent of women fall into different height ranges.\n\n**13. What percent of women are shorter than 154 cm?**\n\nFor example, what percent of women are shorter than 154 centimeters? We can answer this using the pnorm function, which takes the area of the normal distribution less than some number. We pass in the number of interest, 154, as well as the mean and standard deviation of the normal distribution we're using. This gives us about 16% of women are shorter than 154 centimeters.\n\n**14. What percent of women are taller than 154 cm?**\n\nTo find the percent of women taller than 154 centimeters, we can add lower-dot-tail equals FALSE, which will take the area to the right of the first argument.\n\n**15. What percent of women are 154-157 cm?**\n\nTo get the percent of women between 154 and 157 centimeters tall we can take the area below 157 and subtract the area below 154, which leaves us the area between 154 and 157.\n\n**16. What percent of women are 154-157 cm?**\n\nwhich leaves us the area between 154 and 157.\n\n**17. What height are 90% of women shorter than?**\n\nWe can also calculate percentages from heights using qnorm. To figure out what height 90% of women are shorter than, we pass 0-point-9 into qnorm along with the same mean and standard deviation we've been working with. This tells us that 90% of women are shorter than 170 centimeters tall.\n\n**18. What height are 90% of women taller than?**\n\nSimilarly, we can figure out the height 90% of women are taller than by setting the lower-dot-tail argument of qnorm to FALSE.\n\n**19. Generating random numbers**\n\nJust like with other distributions, we can generate random numbers from a normal distribution using rnorm, passing in the sample size we want along with the distribution's mean and standard deviation. Here, we've generated 10 more random heights.\n\n**20. Let's practice!**\n\nTime to practice using the normal distribution!\n\n## Distribution of Amir's sales\n\nSince each deal Amir worked on (both won and lost) was different, each was worth a different amount of money. These values are stored in the `amount` column of `amir_deals` As part of Amir's performance review, you want to be able to estimate the probability of him selling different amounts, but before you can do this, you'll need to determine what kind of distribution the `amount` variable follows.\n\n**Steps**\n\n1. Create a histogram with 10 bins to visualize the distribution of the `amount`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Histogram of amount with 10 bins\nggplot(amir_deals, aes(amount)) +\n    geom_histogram(bins = 10)\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-41-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n> *Question*\n> ---\n> Which probability distribution do the sales amounts most closely follow?<br>\n> <br>\n> ⬜ Uniform<br>\n> ⬜ Binomial<br>\n> ✅ Normal<br>\n> ⬜ None of the above<br>\n\nFabulous work! Now that you've visualized the data, you know that you can approximate probabilities of different `amount`s using the normal distribution.\n\n## Probabilities from the normal distribution\n\nSince each deal Amir worked on (both won and lost) was different, each was worth a different amount of money. These values are stored in the `amount` column of `amir_deals` and follow a normal distribution with a mean of 5000 dollars and a standard deviation of 2000 dollars. As part of his performance metrics, you want to calculate the probability of Amir closing a deal worth various amounts.\n\n**Steps**\n\n1. What's the probability of Amir closing a deal worth less than $7500?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of deal < 7500\npnorm(7500, 5000, 2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.8943502\n```\n:::\n:::\n\n\n2. What's the probability of Amir closing a deal worth more than $1000?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of deal > 1000\npnorm(1000, 5000, 2000, lower.tail=F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.9772499\n```\n:::\n:::\n\n\n3. What's the probability of Amir closing a deal worth between $3000 and $7000?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of deal between 3000 and 7000\npnorm(7000, 5000, 2000) - pnorm(3000, 5000, 2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.6826895\n```\n:::\n:::\n\n\n4. What amount will 75% of Amir's sales be *more than*?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Calculate amount that 75% of deals will be more than\nqnorm(0.75, 5000, 2000, lower.tail =F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 3651.02\n```\n:::\n:::\n\n\nNifty normal distribution usage! You know that you can count on Amir 75% of the time to make a sale worth at least $3651.02, and this information will be useful in making company-wide sales projections.\n\n## Simulating sales under new market conditions\n\nThe company's financial analyst is predicting that next quarter, the worth of each sale will increase by 20% and the volatility, or standard deviation, of each sale's worth will increase by 30%. To see what Amir's sales might look like next quarter under these new market conditions, you'll simulate new sales amounts using the normal distribution and store these in the `new_sales` data frame, which has already been created for you.\n\n**Steps**\n\n1. Currently, Amir's average sale amount is $5000. Calculate what his new average amount will be if it increases by 20% and store this in `new_mean`.\n2. Amir's current standard deviation is $2000. Calculate what his new standard deviation will be if it increases by 30% and store this in `new_sd`.\n3. Add a new column called `amount` to the data frame `new_sales`, which contains 36 simulated amounts from a normal distribution with a mean of `new_mean` and a standard deviation of `new_sd`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_sales <- tibble(sale_num = c(1:36))\n\n# Calculate new average amount\nnew_mean <- 5000 * 1.2\n\n# Calculate new standard deviation\nnew_sd <- 2000 * 1.3\n\n# Simulate 36 sales\nnew_sales <- new_sales %>% \n  mutate(amount = rnorm(36, new_mean, new_sd))\n```\n:::\n\n\n4. Plot the distribution of the `new_sales` `amount`s using a histogram with 10 bins.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 4. Create histogram with 10 bins\nggplot(new_sales, aes(amount)) +\n  geom_histogram(bins = 10)\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-47-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nSuccessful simulating! Although the average sale amount went up, the variation also increased, so it's not straightforward to decide whether these sales are better than his current ones. In the next exercise, you'll explore the effects of higher variation.\n\n## Which market is better?\n\nThe key metric that the company uses to evaluate salespeople is the percent of sales they make over $1000 since the time put into each sale is usually worth a bit more than that, so the higher this metric, the better the salesperson is performing. \n\nRecall that Amir's current sales amounts have a mean of $5000 and a standard deviation of $2000, and Amir's predicted amounts in next quarter's market have a mean of $6000 and a standard deviation of $2600.\n\n> *Question*\n> ---\n> Based only on the metric of **percent of sales over $1000**, does Amir perform better in the current market or the predicted market?<br>\n> <br>\n> ⬜ Amir performs much better in the current market.<br>\n> ⬜ Amir performs much better in next quarter's predicted market.<br>\n> ✅ Amir performs about equally in both markets.<br>\n\nGreat work! In the current market, Amir makes sales over $1000 about 97.7% of the time, and about 97.3% of the time in the predicted market, so there's not much of a difference. However, his average sale amount is higher in the predicted market, so the company may want to consider other metrics as well. \n\n## The central limit theorem\n\nTheory. Coming soon ...\n\n\n**1. The central limit theorem**\n\nNow that you're familiar with the normal distribution, it's time to learn about what makes it so important.\n\n**2. Rolling the dice 5 times**\n\nLet's go back to our dice rolling example. We have a vector of the numbers 1 to 6 called die. To simulate rolling the die 5 times, we'll use the sample() function. sample() works the same way as sample_n(), except it samples from a vector instead of a data frame. We pass in the vector we want to sample from, the size of the sample, and set replace to TRUE.This gives us the results of 5 rolls.Now, we'll take the mean of the 5 rolls, which gives us 2.\n\n**3. Rolling the dice 5 times**\n\nIf we roll another 5 times and take the mean, we get a different mean. If we do it again, we get another mean.\n\n**4. Rolling the dice 5 times 10 times**\n\nLet's repeat this 10 times: we'll roll 5 times and take the mean.To do this, we'll use replicate. We pass in 10 so that the process is repeated 10 times, followed by the snippet of code we want to be run, which is the rolling and averaging.This returns a vector of 10 different sample means.Let's plot these sample means.\n\n**5. Sampling distributions**\n\nA distribution of a summary statistic like this is called a sampling distribution. This distribution, specifically, is a sampling distribution of the sample mean.\n\n**6. 100 sample means**\n\nNow let's do this 100 times. If we look at the new sampling distribution, its shape somewhat resembles the normal distribution, even though the distribution of the die is uniform.\n\n**7. 1000 sample means**\n\nLet's take 1000 means. This sampling distribution more closely resembles the normal distribution.\n\n**8. Central limit theorem**\n\nThis phenomenon is known as the central limit theorem, which states that a sampling distribution will approach a normal distribution as the number of trials increases.In our example, the sampling distribution became closer to the normal distribution as we took more and more sample means.It's important to note that the central limit theorem only applies when samples are taken randomly and are independent, for example, randomly picking sales deals with replacement.\n\n**9. Standard deviation and the CLT**\n\nThe central limit theorem, or CLT, applies to other summary statistics as well.If we take the standard deviation of 5 rolls 1000 times, the sample standard deviations are distributed normally, centered around 1-point-9, which is the distribution's standard deviation.\n\n**10. Proportions and the CLT**\n\nAnother statistic that the CLT applies to is proportion.Let's sample from the sales team 10 times with replacement and see how many draws have Claire as the outcome. In this case, 10% of draws were Claire. If we draw again, there are 40% Claires.\n\n**11. Sampling distribution of proportion**\n\nIf we repeat this 1000 times and plot the distribution of the sample proportions, it resembles a normal distribution centered around 0-point-25, since Claire's name was on 25% of the tickets.\n\n**12. Mean of sampling distribution**\n\nSince these sampling distributions are normal, we can take their mean to get an estimate of a distribution's mean, standard deviation, or proportion.If we take the mean of our sample means from earlier, we get 3-point-48. That's pretty close to the expected value, which is 3-point-5!Similarly, the mean of the sample proportions of Claires isn't far off from 0-point-25.In these examples, we know what the underlying distributions look like, but if we don't, this can be a useful method for estimating characteristics of an underlying distribution.The central limit theorem also comes in handy when you have a huge population and don't have the time or resources to collect data on everyone. Instead, you can collect several smaller samples and create a sampling distribution to estimate what the mean or standard deviation is.\n\n**13. Let's practice!**\n\nNow, it's time to practice utilizing the central limit theorem.\n\n## Visualizing sampling distributions\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Function to resample distributions\nresample_dist <- function(x, sample_mean = 100000, sample_size = 20) {\n  replicate(n    = sample_mean,\n            expr = mean(sample(x       = x,\n                               size    = sample_size,\n                               replace = TRUE)))\n}\n\n# Set seed\nset.seed(1234)\n\nn <- 4000\n# 1 Exponential Distribution\nx_exp    <- rexp(n = n, rate = 0.1)\ndist_exp <- resample_dist(x_exp)\n\n# 2 Uniform Distribution\nx_unif    <- runif(n = n, min = 0, max = 1)\ndist_unif <- resample_dist(x_unif)\n\n# 3 Normal Distribution\nx_norm    <-rnorm(n = n, mean = 0, sd = 1)\ndist_norm <- resample_dist(x_norm)\n\n# 4 Binomial Distribution\nx_binom    <- rbinom(n = n, size = 500, prob = 0.7)\ndist_binom <- resample_dist(x_binom)\n\n# 5 Chisquare Distribution\nx_chisq    <- rchisq(n = 4000, df = 10, ncp = 1)\ndist_chisq <- resample_dist(x_binom)\n\n\n# Bind data together\nbind_rows( tibble(values = x_exp,      dist = \"Exponential Distribution\", var = \"Histogram\") )   |> \nbind_rows( tibble(values = dist_exp,   dist = \"Exponential Distribution\", var = \"Histogram of Resampling Distribution\") ) |> \nbind_rows( tibble(values = x_unif,     dist = \"Uniform Distribution\",     var = \"Histogram\") ) |> \nbind_rows( tibble(values = dist_unif,  dist = \"Uniform Distribution\",     var = \"Histogram of Resampling Distribution\") ) |> \nbind_rows( tibble(values = x_norm,     dist = \"Normal Distribution\",      var = \"Histogram\") ) |>\nbind_rows( tibble(values = dist_norm,  dist = \"Normal Distribution\",      var = \"Histogram of Resampling Distribution\") ) |> \nbind_rows( tibble(values = x_binom,    dist = \"Binomial Distribution\",    var = \"Histogram\") ) |>\nbind_rows( tibble(values = dist_binom, dist = \"Binomial Distribution\",    var = \"Histogram of Resampling Distribution\") ) |> \nbind_rows( tibble(values = x_chisq,    dist = \"Chisquare Distribution\",   var = \"Histogram\") ) |>\nbind_rows( tibble(values = dist_chisq, dist = \"Chisquare Distribution\",   var = \"Histogram of Resampling Distribution\") ) |> \n\n# Change order\nmutate(dist = dist |> forcats::fct_relevel(\"Exponential Distribution\",\n                                           \"Uniform Distribution\",\n                                           \"Normal Distribution\",\n                                           \"Binomial Distribution\")) |> \n# Plot\nggplot(aes(values)) + \n  geom_histogram() +\n  facet_wrap(vars(dist, var), scales = \"free\", dir = \"v\", nrow = 2) +\n  theme(axis.title = element_blank(),\n        axis.text  = element_blank(),\n        axis.ticks = element_blank())\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.\n```\n:::\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-48-1.png){fig-align='center' width=672}\n:::\n:::\n\nhttps://audhiaprilliant.medium.com/the-statistics-simulation-of-central-limit-theorem-and-law-of-large-number-b4e489a139c4\n\n> *Question*\n> ---\n> Try creating sampling distributions of different summary statistics from samples of different distributions. Which distribution does the central limit theorem not apply to?<br>\n> <br>\n> ⬜ Discrete uniform distribution<br>\n> ⬜ Continuous uniform distribution<br>\n> ⬜ Binomial distribution<br>\n> ⬜ All of the above<br>\n> ✅ None of the above<br>\n\nVictorious visualizing! Regardless of the shape of the distribution you're taking sample means from, the central limit theorem will apply if the sampling distribution contains enough sample means.\n\n## The CLT in action\n\nThe central limit theorem states that a sampling distribution of a sample statistic approaches the normal distribution as you take more samples, no matter the original distribution being sampled from.\n\nIn this exercise, you'll focus on the sample mean and see the central limit theorem in action while examining the `num_users` column of `amir_deals` more closely, which contains the number of people who intend to use the product Amir is selling.\n\n**Steps**\n\n1. Create a histogram of the `num_users` column of `amir_deals`. Use 10 bins.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Create a histogram of num_users\nggplot(amir_deals, aes(num_users)) +\n    geom_histogram(bins = 10)\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-49-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n2. Set the seed to `104`.\n3. Take a sample of size `20` with replacement from the `num_users` column of `amir_deals`, and take the mean.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. Set seed to 104\nset.seed(104)\n\n# 3. Sample 20 num_users with replacement from amir_deals\nsample(amir_deals$num_users, 20, replace = T) %>%\n  # Take mean\n  mean()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 30.35\n```\n:::\n:::\n\n\n4. Repeat this 100 times and store as `sample_means`. This will take 100 different samples and calculate the mean of each.\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(104)\n# 4. Repeat the above 100 times\nsample_means <- replicate(100, sample(amir_deals$num_users, size = 20, replace = TRUE) %>% mean())\n```\n:::\n\n\n5. A data frame called `samples` has been created for you with a column `mean`, which contains the values from `sample_means`. Create a histogram of the `mean` column with 10 bins.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Set seed to 104\nset.seed(104)\n\n\n# Create data frame for plotting\nsamples <- data.frame(mean = sample_means)\n\n# Histogram of sample means\nggplot(samples, aes(mean)) +\n  geom_histogram(bins=10)\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-52-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nFabulous job! You've just seen the central limit thorem at work. Even though the distribution of `num_users` is not normal, the distribution of its sample mean resembles the normal distribution.\n\n## The mean of means\n\nYou want to know what the average number of users (`num_users`) is per deal, but you want to know this number for the entire company so that you can see if Amir's deals have more or fewer users than the company's average deal. The problem is that over the past year, the company has worked on more than ten thousand deals, so it's not realistic to compile all the data. Instead, you'll estimate the mean by taking several random samples of deals, since this is much easier than collecting data from everyone in the company.\n\nThe user data for all the company's deals is available in `all_deals`.\n\n**Steps**\n\n1. Set the random seed to `321`.\n2. Take 30 samples of size 20 from `all_deals$num_users` and take the mean of each sample. Store the sample means in `sample_means`.\n3. Take the mean of `sample_means`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nall_deals <- readRDS(\"data/all_deals.rds\")\n\n# 1. Set seed to 321\nset.seed(321)\n\n# 2. Take 30 samples of 20 values of num_users, take mean of each sample\nsample_means <- replicate(30, sample(x = all_deals$num_users, size = 20) %>% mean())\n\n# 3. Calculate mean of sample_means\nmean(sample_means)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 37.02667\n```\n:::\n:::\n\n\n4. Take the mean of the `num_users` column of `amir_deals`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 4. Calculate mean of num_users in amir_deals\nmean(amir_deals$num_users)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 37.65169\n```\n:::\n:::\n\n\nMagnificent mean calculation! Amir's average number of users is very close to the overall average, so it looks like he's meeting expectations. Make sure to note this in his performance review!\n\n## The Poisson distribution\n\nTheory. Coming soon ...\n\n\n**1. The Poisson distribution**\n\nIn this video, we'll talk about another probability distribution called the Poisson distribution.\n\n**2. Poisson processes**\n\nBefore we talk about probability, let's define a Poisson process.A Poisson process is a process where events appear to happen at a certain rate, but completely at random. For example, the number of animals adopted from an animal shelter each week is a Poisson process - we may know that on average there are 8 adoptions per week, but this number can differ randomly. Other examples would be the number of people arriving at a restaurant each hour, or the number of earthquakes per year in California.\n\n**3. Poisson distribution**\n\nThe Poisson distribution describes the probability of some number of events happening over a fixed period of time. We can use the Poisson distribution to calculate the probability of at least 5 animals getting adopted in a week, the probability of 12 people arriving in a restaurant in an hour, or the probability of fewer than 20 earthquakes in California in a year.\n\n**4. Lambda ($\\lambda$)**\n\nThe Poisson distribution is described by a value called lambda, which represents the average number of events per time period. In the animal shelter example, this would be the average number of adoptions per week, which is 8. This value is also the expected value of the distribution!The Poisson distribution with lambda equals 8 looks like this. Notice that it's a discrete distribution since we're counting events, and 7 and 8 are the most likely number of adoptions to happen in a week.\n\n**5. Lambda is the distribution's peak**\n\nLambda changes the shape of the distribution, so a Poisson distribution with lambda equals 1, in red, looks quite different than a Poisson distribution with lambda equals 8, in blue, but no matter what, the distribution's peak is always at its lambda value.\n\n**6. Probability of a single value**\n\nGiven that the average number of adoptions per week is 8, what's the probability of 5 adoptions in a week? We'll use the dpois function, passing 5 as the first argument and 8 as the second argument to indicate the distribution's mean. This gives us about 9%.\n\n**7. Probability of less than or equal to**\n\nTo get the probability that 5 or fewer adoptions will happen in a week, use the ppois function, passing in the same numbers. This gives us about 20%.\n\n**8. Probability of greater than**\n\nJust like other probability functions you've learned about so far, use the lower-dot-tail argument to get the probability of more than 5 adoptions. There's an 81% chance that more than 5 adoptions will occur.If the average number of adoptions rises to 10 per week, there will be a 93% chance that more than 5 adoptions will occur.\n\n**9. Sampling from a Poisson distribution**\n\nJust like other distributions, we can take samples from Poisson distributions using rpois. Here, we'll simulate 10 different weeks at the animal shelter. In one week, there are 13 adoptions, but only 3 in another.\n\n**10. The CLT still applies!**\n\nJust like other distributions, the sampling distribution of sample means of a Poisson distribution looks normal with a large number of samples.\n\n**11. Let's practice!**\n\nTime to practice taking Poisson probabilities!\n\n## Identifying lambda\n\nNow that you've learned about the Poisson distribution, you know that its shape is described by a value called lambda. In this exercise, you'll match histograms to lambda values.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nc(1,2,5,10,20) |> \n  set_names() |>\n  map(rpois, n = 10000) |> \n  map(as_tibble) |> \n  bind_rows(.id = \"lambda\") |> \n  mutate(lambda = lambda |> forcats::fct_inorder()) |> \n  ggplot(aes(x=value)) + \n  geom_density(aes(group = lambda, color=lambda, fill=lambda), adjust = 4, alpha = 1/3) +\n  scale_color_discrete() + \n  scale_fill_discrete() + \n  ggtitle(\"Probability Mass Function\")\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-55-1.png){fig-align='center' width=672}\n:::\n:::\n\n\nMatch each Poisson distribution to its lambda value.\n\n## Tracking lead responses\n\nYour company uses sales software to keep track of new sales leads. It organizes them into a queue so that anyone can follow up on one when they have a bit of free time. Since the number of lead responses is a countable outcome over a period of time, this scenario corresponds to a Poisson distribution. On average, Amir responds to 4 leads each day. In this exercise, you'll calculate probabilities of Amir responding to different numbers of leads.\n\n**Steps**\n\n1. What's the probability that Amir responds to 5 leads in a day, given that he responds to an average of 4?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Probability of 5 responses\ndpois(5, lambda = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.1562935\n```\n:::\n:::\n\n\n2. Amir's coworker responds to an average of 5.5 leads per day. What is the probability that she answers 5 leads in a day?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. Probability of 5 responses from coworker\ndpois(5, 5.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.1714007\n```\n:::\n:::\n\n\n3. What's the probability that Amir responds to 2 or fewer leads in a day?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of 2 or fewer responses\nppois(2, 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.2381033\n```\n:::\n:::\n\n\n4. What's the probability that Amir responds to more than 10 leads in a day?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability of > 10 responses\nppois(10, 4, lower.tail =F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.002839766\n```\n:::\n:::\n\n\nPerfect Poisson probabilities! Note that if you provide `dpois()` or `ppois()` with a non-integer, it returns 0 and throws a warning since the Poisson distribution only applies to integers.\n\n## More probability distributions\n\nTheory. Coming soon ...\n\n\n**1. More probability distributions**\n\nIn this lesson, we'll discuss a few other probability distributions.\n\n**2. Exponential distribution**\n\nThe first distribution is the exponential distribution, which represents the probability of a certain time passing between Poisson events. We can use the exponential distribution to predict, for example, the probability of more than 1 day between adoptions, the probability of fewer than 10 minutes between restaurant arrivals, and the probability of 6-8 months passing between earthquakes. The exponential distribution uses the same lambda value, which represents the rate, that the Poisson distribution does. Note that lambda and rate mean the same value in this context.It's also continuous, unlike the Poisson distribution, since it represents time.\n\n**3. Customer service requests**\n\nFor example, let's say that one customer service ticket is created every 2 minutes. We can rephrase this so it's in terms of a time interval of one minute, so half of a ticket is created each minute. We'll use 0-point-5 as the lambda value.The exponential distribution with a rate of one half looks like this.\n\n**4. Lambda in exponential distribution**\n\nThe rate affects the shape of the distribution and how steeply it declines.\n\n**5. How long until a new request is created?**\n\nSimilar to other continuous distributions, we can use pexp to calculate probabilities.The probability of waiting less than 1 minute for a new request is calculated using pexp, passing in 1 and 0-point-5 as the rate, which gives us about a 40% chance.The probability of waiting more than 4 minutes can be found using lower-dot-tail equals FALSE, giving a 13% chance.Finally, the probability of waiting between 1 and 4 minutes can be found by taking pexp of 4 and subtracting pexp of 1. There's a 50% chance you'll wait between 1 and 4 minutes.\n\n**6. Expected value of exponential distribution**\n\nRecall that lambda is the expected value of the Poisson distribution, which measures frequency in terms of rate or number of events. In our customer service ticket example, this means that the expected number of requests per minute is 0-point-5.The exponential distribution measures frequency in terms of time between events. The expected value of the exponential distribution can be calculated by taking 1 divided by lambda. In our example, the expected time between requests is 1 over one half, which is 2, so there is an average of 2 minutes between requests.\n\n**7. (Student's) t-distribution**\n\nThe next distribution is the t-distribution, which is also sometimes called Student's t-distribution. Its shape is similar to the normal distribution, but not quite the same.If we compare the normal distribution, in red, with the t-distribution with one degree of freedom, in blue, the t-distribution's tails are thicker. This means that in a t-distribution, observations are more likely to fall further from the mean.\n\n**8. Degrees of freedom**\n\nThe t-distribution has a parameter called degrees of freedom, which affects the thickness of the distribution's tails. Lower degrees of freedom results in thicker tails and a higher standard deviation. As the number of degrees of freedom increases, the distribution looks more and more like the normal distribution.\n\n**9. Log-normal distribution**\n\nThe last distribution we'll discuss is the log-normal distribution. Variables that follow a log-normal distribution have a logarithm that is normally distributed.This results in distributions that are skewed, unlike the normal distribution.There are lots of real-world examples that follow this distribution, such as the length of chess games, blood pressure in adults, and the number of hospitalizations in the 2003 SARS outbreak.\n\n**10. Let's practice!**\n\nIn addition to the three in this video, there are lots of other probability distributions that are out of the scope of this course, but that you can learn about in other DataCamp courses. For now, it's time to practice the distributions you've learned so far!\n\n## Too many distributions\n\nBy this point, you've learned about so many different probability distributions that it can be difficult to remember which is which. In this exercise, you'll practice distinguishing between distributions and identifying the distribution that best matches different scenarios.\n\nMatch each situation to the distribution that best models it.\n\n| Poisson | Exponential | Binomial |\n| --- | --- | --- |\n| Number of customers that enter a store each hour | Amount of time until the next customer makes a purchase | Number of people from a group of 30 that pass their driving test |\n| Number of products sold each week | Amount of time until someone pays off their loan | |\n\n## Modeling time between leads\n\nTo further evaluate Amir's performance, you want to know how much time it takes him to respond to a lead after he opens it. On average, it takes 2.5 hours for him to respond. In this exercise, you'll calculate probabilities of different amounts of time passing between Amir receiving a lead and sending a response.\n\n\n**Steps**\n\n1. What's the probability it takes Amir less than an hour to respond to a lead?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability response takes < 1 hour\npexp(1, rate = 0.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.32968\n```\n:::\n:::\n\n\n2. What's the probability it takes Amir more than 4 hours to respond to a lead?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability response takes > 4 hours\npexp(4, rate = 0.4, lower.tail = F)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.2018965\n```\n:::\n:::\n\n\n3. What's the probability it takes Amir 3-4 hours to respond to a lead?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Probability response takes 3-4 hours\npexp(4, 0.4) - pexp(3, 0.4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.09929769\n```\n:::\n:::\n\n\nExcellent exponential computations! There's only about a 20% chance it will take Amir more than 4 hours to respond, so he's pretty speedy in his responses.\n\n## The t-distribution\n\n> *Question*\n> ---\n> Which statement is **not** true regarding the t-distribution?<br>\n> <br>\n> ⬜ The t-distribution has thicker tails than the normal distribution.<br>\n> ⬜ A t-distribution with high degrees of freedom resembles the normal distribution.<br>\n> ⬜ The number of degrees of freedom affects the distribution's variance.<br>\n> ✅ The t-distribution is skewed.<br>\n\nTerrific! The t-distribution is not skewed, just like the normal distribution, but it does have thicker tails and higher variance than the normal distribution.\n\n# 4. Correlation and Experimental Design\n\nIn this chapter, you'll learn how to quantify the strength of a linear relationship between two variables, and explore how confounding variables can affect the relationship between two other variables. You'll also see how a study’s design can influence its results, change how the data should be analyzed, and potentially affect the reliability of your conclusions.\n\n## Correlation\n\nTheory. Coming soon ...\n\n\n**1. Correlation**\n\nWelcome to the final chapter of the course, where we'll talk about correlation and experimental design.\n\n**2. Relationships between two variables**\n\nBefore we dive in, let's talk about relationships between numeric variables. We can visualize these kinds of relationships with scatterplots - in this scatterplot, we can see the relationship between the total amount of sleep mammals get and the amount of REM sleep they get.The variable on the x-axis is called the explanatory or independent variable, and the variable on the y-axis is called the response or dependent variable.\n\n**3. Correlation coefficient**\n\nWe can also examine relationships between two numeric variables using a number called the correlation coefficient. This is a number between -1 and 1, where the magnitude corresponds to the strength of the relationship between the variables, and the sign, positive or negative, corresponds to the direction of the relationship.\n\n**4. Magnitude = strength of relationship**\n\nHere's a scatterplot of 2 variables, x and y, that have a correlation coefficient of 0-point-99. Since the data points are closely clustered around a line, we can describe this as a near-perfect or very strong relationship. If we know what x is, we'll have a pretty good idea of what the value of y could be.\n\n**5. Magnitude = strength of relationship**\n\nHere, x and y have a correlation coefficient of 0-point-75, and the data points are more spread out.\n\n**6. Magnitude = strength of relationship**\n\nIn this plot, x and y have a correlation of 0-point-56 and are therefore moderately correlated.\n\n**7. Magnitude = strength of relationship**\n\nA correlation coefficient around 0-point-2 would be considered a weak relationship.\n\n**8. Magnitude = strength of relationship**\n\nWhen the correlation coefficient is close to 0, x and y have no relationship and the scatterplot looks completely random. This means that knowing the value of x doesn't tell us anything about the value of y.\n\n**9. Sign = direction**\n\nThe sign of the correlation coefficient corresponds to the direction of the relationship. A positive correlation coefficient indicates that as x increases, y also increases. A negative correlation coefficient indicates that as x increases, y decreases.\n\n**10. Visualizing relationships**\n\nTo visualize relationships between two variables, we can use a scatterplot created using geom_point.\n\n**11. Adding a trendline**\n\nWe can add a linear trendline to the scatterplot using geom_smooth. We'll set the method argument to \"lm\" to indicate that we want a linear trendline, and se to FALSE so that there aren't error margins around the line.Trendlines like this can be helpful to more easily see a relationship between two variables.\n\n**12. Computing correlation**\n\nTo calculate the correlation coefficient between two variables in R, we can use the cor function. The cor function takes in two numeric vectors and will return their correlation coefficient.Note that it doesn't matter which order the vectors are passed into the function since the correlation between x and y is the same thing as the correlation between y and x.\n\n**13. Correlation with missing values**\n\nIf you have any missing values in either variable, R will return NA when you calculate correlation. To ignore data points where one or both values are missing, set the use argument of cor to pairwise-dot-complete-dot-obs.\n\n**14. Many ways to calculate correlation**\n\nThere's more than one way to calculate correlation, but the method we've been using in this video is called the Pearson product-moment correlation, which is also written as r. This is the most commonly used measure of correlation. Mathematically, it's calculated using this formula where x and y bar are the means of x and y, and sigma x and sigma y are the standard deviations of x and y.The formula itself isn't important to memorize, but know that there are variations of this formula that measure correlation a bit differently, such as Kendall's tau and Spearman's rho, but those are beyond the scope of this course.\n\n**15. Let's practice!**\n\nOkay, time to practice calculating correlations.\n\n## Guess the correlation\n\n> *Question*\n> ---\n> Which of the following statements is NOT true about correlation?<br>\n> <br>\n> ⬜ If the correlation between `x` and `y` has a high magnitude, the data points will be clustered closely around a line.<br>\n> ⬜ Correlation can be written as *r*.<br>\n> ⬜ If `x` and `y` are negatively correlated, values of `y` decrease as values of `x` increase.<br>\n> ✅ Correlation cannot be 0.<br>\n\nSpot on! When correlation is 0, that means there is no relationship between two variables and the points appear to be randomly scattered.\n\n## Relationships between variables\n\nIn this chapter, you'll be working with a dataset `world_happiness` containing results from the <a href=\"https://worldhappiness.report/ed/2019/\" target=\"_blank\" rel=\"noopener noreferrer\">2019 World Happiness Report</a>. The report scores various countries based on how happy people in that country are. It also ranks each country on various societal aspects such as social support, freedom, corruption, and others. The dataset also includes the GDP per capita and life expectancy for each country.\n\nIn this exercise, you'll examine the relationship between a country's life expectancy (`life_exp`) and happiness score (`happiness_score`) both visually and quantitatively. Both `dplyr` and `ggplot2` are loaded and `world_happiness` is available.\n\n**Steps**\n\n1. Create a scatterplot of `happiness_score` vs. `life_exp` using `ggplot2`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nworld_happiness <- readRDS(\"data/world_happiness_sugar.rds\")\n\n# 1. Create a scatterplot of happiness_score vs. life_exp\nggplot(world_happiness, aes(x = life_exp, y = happiness_score)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-63-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n2. Add a linear trendline to the scatterplot, setting `se` to `FALSE`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. Add a linear trendline to scatterplot\nggplot(world_happiness, aes(life_exp, happiness_score)) +\n  geom_point() +\n  geom_smooth(method = \"lm\", se = F)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n#> `geom_smooth()` using formula = 'y ~ x'\n```\n:::\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-64-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n> *Question*\n> ---\n> Based on the scatterplot, which is most likely the correlation between `life_exp` and `happiness_score`?<br>\n> <br>\n> ⬜ 0.3<br>\n> ⬜ -0.3<br>\n> ✅ 0.8<br>\n> ⬜ -0.8<br>\n\n3. Calculate the correlation between `life_exp` and `happiness_score`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 3. Correlation between life_exp and happiness_score\ncor(world_happiness$life_exp, world_happiness$happiness_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.7737615\n```\n:::\n:::\n\nVibrant visualizations! Scatterplots with trendlines are a great way to verify that a relationship between two variables is indeed linear.\n\n## Correlation caveats\n\nTheory. Coming soon ...\n\n\n**1. Correlation caveats**\n\nWhile correlation is a useful way to quantify relationships, there are some caveats.\n\n**2. Non-linear relationships**\n\nConsider this data. There is clearly a relationship between x and y, but when we calculate the correlation, we get 0-point-18.\n\n**3. Non-linear relationships**\n\nThis is because the relationship between the two variables is a quadratic relationship, not a linear relationship. The correlation coefficient measures the strength of linear relationships, and linear relationships only.\n\n**4. Correlation only accounts for linear relationships**\n\nJust like any summary statistic, correlation shouldn't be used blindly, and you should always visualize your data when possible.\n\n**5. Mammal sleep data**\n\nLet's return to the mammal sleep data we discussed in chapter 1.\n\n**6. Body weight vs. awake time**\n\nHere's a scatterplot of each mammal's body weight versus the time they spend awake each day. The relationship between these variables is definitely not a linear one.The correlation between body weight and awake time is only about 0-point-3, which is a weak linear relationship.\n\n**7. Distribution of body weight**\n\nIf we take a closer look at the distribution of body weight, it's highly skewed. There are lots of lower weights and a few weights that are much higher than the rest.\n\n**8. Log transformation**\n\nWhen data is highly skewed like this, we can apply a log transformation. We'll create a new column called log_bodywt which holds the log of each body weight.If we plot the log of bodyweight versus awake time, the relationship looks much more linear than the one between regular bodyweight and awake time.The correlation between the log of bodyweight and awake time is about 0-point-57, which is much higher than the 0-point-3 we had before.\n\n**9. Other transformations**\n\nIn addition to the log transformation, there are lots of other transformations that can be used to make a relationship more linear, like taking the square root or reciprocal of a variable. The choice of transformation will depend on the data and how skewed it is. These can be applied in different combinations to x and y, for example, you could apply a log transformation to both x and y, or a square root transformation to x and a reciprocal transformation to y.\n\n**10. Why use a transformation?**\n\nSo why use a transformation?Certain statistical methods rely on variables having a linear relationship, like calculating a correlation coefficient. Linear regression is another statistical technique that requires variables to be related in a linear manner, which you can learn all about in this course.\n\n**11. Correlation does not imply causation**\n\nLet's talk about another important caveat of correlation that you may have heard about before: correlation does not imply causation. This means that if x and y are correlated, x doesn't necessarily cause y.For example, here's a scatterplot of the per capita margarine consumption in the US each year versus the divorce rate in the state of Maine. The correlation between these two variables is 0-point-99, which is nearly perfect. However, this doesn't mean that consuming more margarine will cause more divorces. This kind of correlation is often called a spurious correlation.\n\n**12. Confounding**\n\nA phenomenon called confounding can lead to spurious correlations.Let's say we want to know if drinking coffee causes lung cancer. Looking at the data, we find that coffee drinking and lung cancer are correlated, which may lead us to think that drinking more coffee will give you lung cancer.\n\n**13. Confounding**\n\nHowever, there is a third, hidden variable at play, which is smoking.\n\n**14. Confounding**\n\nSmoking is known to be associated with coffee consumption.\n\n**15. Confounding**\n\nIt is also known that smoking causes lung cancer.\n\n**16. Confounding**\n\nIn reality, it turns out that coffee does not cause lung cancer and is only associated with it, but it appeared causal due to the third variable, smoking.This third variable is called a confounder, or lurking variable. This means that the relationship of interest between coffee and lung cancer is a spurious correlation.Another example of this is the relationship between holidays retail sales. While it might be that people buy more around holidays as a way of celebrating, it's hard to tell how much of the increased sales is due to holidays, and how much is due to the special deals and promotions that often run around holidays. Here, special deals confound the relationship between holidays and sales.\n\n**17. Let's practice!**\n\nNow that you've learned how to use correlation responsibly, time to practice.\n\n## What can't correlation measure?\n\nWhile the correlation coefficient is a convenient way to quantify the strength of a relationship between two variables, it's far from perfect. In this exercise, you'll explore one of the caveats of the correlation coefficient by examining the relationship between a country's GDP per capita (`gdp_per_cap`) and happiness score.\n\n**Steps**\n\n1. Create a scatterplot showing the relationship between `gdp_per_cap` (on the x-axis) and `life_exp` (on the y-axis).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Scatterplot of gdp_per_cap and life_exp\nggplot(world_happiness, aes(x = gdp_per_cap, y = life_exp)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-66-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n2. Calculate the correlation between `gdp_per_cap` and `life_exp`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Correlation between gdp_per_cap and life_exp\ncor(world_happiness$gdp_per_cap, world_happiness$life_exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.7235027\n```\n:::\n:::\n\n\n> *Question*\n> ---\n> The correlation between GDP per capita and life expectancy is 0.7. Why is correlation not the best way to measure the relationship between the two variables?<br>\n> <br>\n> ⬜ Correlation measures how one variable affects another.<br>\n> ✅ Correlation only measures linear relationships.<br>\n> ⬜ Correlation cannot properly measure relationships between numeric variables.<br>\n\nCorrect! The correlation coefficient can't account for any relationships that aren't linear, regardless of strength. \n  \n## Transforming variables\n\nWhen variables have skewed distributions, they often require a transformation in order to form a linear relationship with another variable so that correlation can be computed. In this exercise, you'll perform a transformation yourself.\n\n**Steps**\n\n1. Create a scatterplot of `happiness_score` versus `gdp_per_cap`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 1. Scatterplot of happiness_score vs. gdp_per_cap\nggplot(world_happiness, aes(x=gdp_per_cap, y = happiness_score)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-68-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n2. Calculate the correlation between `happiness_score` and `gdp_per_cap`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 2. Calculate correlation\ncor(world_happiness$happiness_score, world_happiness$gdp_per_cap)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.7601853\n```\n:::\n:::\n\n\n3. Add a new column to `world_happiness` called `log_gdp_per_cap` that contains the log of `gdp_per_cap`.\n4. Create a scatterplot of `happiness_score` versus `log_gdp_per_cap`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 3. Create log_gdp_per_cap column\nworld_happiness <- world_happiness %>%\n  mutate(log_gdp_per_cap = log(gdp_per_cap))\n\n# 4. Scatterplot of log_gdp_per_cap vs. happiness_score\nggplot(world_happiness, aes(x=log_gdp_per_cap, y=happiness_score)) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-70-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n5. Calculate the correlation between `happiness_score` and `log_gdp_per_cap`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# 5. Calculate correlation\ncor(world_happiness$log_gdp_per_cap, world_happiness$happiness_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.7965484\n```\n:::\n:::\n\n\nTerrific transforming! The relationship between GDP per capita and happiness became more linear by applying a log transformation. Log transformations are great to use on variables with a skewed distribution, such as GDP.\n\n## Does sugar improve happiness?\n\nA new column has been added to `world_happiness` called `grams_sugar_per_day`, which contains the average amount of sugar eaten per person per day in each country. In this exercise, you'll examine the effect of a country's average sugar consumption on its happiness score.\n\n**Steps**\n\n1. Create a scatterplot showing the relationship between `grams_sugar_per_day` (on the x-axis) and `happiness_score` (on the y-axis).\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Scatterplot of grams_sugar_per_day and happiness_score\nggplot(world_happiness, aes(x=grams_sugar_per_day, y = happiness_score)) +\n    geom_point()\n```\n\n::: {.cell-output-display}\n![](01_statistics_beginner_files/figure-html/unnamed-chunk-72-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n2. Calculate the correlation between `grams_sugar_per_day` and `happiness_score`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Correlation between grams_sugar_per_day and happiness_score\ncor(world_happiness$grams_sugar_per_day, world_happiness$happiness_score)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n#> [1] 0.69391\n```\n:::\n:::\n\n\n> *Question*\n> ---\n> Based on this data, which statement about sugar consumption and happiness scores is true?<br>\n> <br>\n> ⬜ Increased sugar consumption leads to a higher happiness score.<br>\n> ⬜ Lower sugar consumption results in a lower happiness score<br>\n> ✅ Increased sugar consumption is associated with a higher happiness score.<br>\n> ⬜ Sugar consumption is not related to happiness.<br>\n\nNice interpretation of correlation! If correlation always implied that one thing causes another, people may do some nonsensical things, like eat more sugar to be happier. \n\n## Confounders\n\nA study is investigating the relationship between neighborhood residence and lung capacity. Researchers measure the lung capacity of thirty people from neighborhood A, which is located near a highway, and thirty people from neighborhood B, which is not near a highway. Both groups have similar smoking habits and a similar gender breakdown. \n\n> *Question*\n> ---\n> Which of the following could be a *confounder* in this study?<br>\n> <br>\n> ⬜  Lung capacity<br>\n> ⬜  Neighborhood<br>\n> ✅  Air pollution<br>\n> ⬜  Smoking status<br>\n> ⬜  Gender<br>\n\nCorrect! You would expect there to be more air pollution in the neighborhood situated near the highway, which can cause lower lung capacity.\n\n## Design of experiments\n\nTheory. Coming soon ...\n\n**1. Design of experiments**\n\nOften, data is created as a result of a study that aims to answer a specific question. However, data needs to be analyzed and interpreted differently depending on how the data was generated and how the study was designed.\n\n**2. Vocabulary**\n\nExperiments generally aim to answer a question in the form, \"What is the effect of the treatment on the response?\" In this setting, treatment refers to the explanatory or independent variable, and response refers to the response or dependent variable. For example, what is the effect of an advertisement on the number of products purchased? In this case, the treatment is an advertisement, and the response is the number of products purchased.\n\n**3. Controlled experiments**\n\nIn a controlled experiment, participants are randomly assigned to either the treatment group or the control group, where the treatment group receives the treatment and the control group does not. In our example, the treatment group will see an advertisement, and the control group will not. Other than this difference, the groups should be comparable so that we can determine if seeing an advertisement causes people to buy more. If the groups aren't comparable, this could lead to confounding, or bias. If the average age of participants in the treatment group is 25 and the average age of participants in the control group is 50, age could be a potential confounder if younger people are more likely to purchase more, and this will make the experiment biased towards the treatment.\n\n**4. The gold standard of experiments will use...**\n\nThe gold standard, or ideal experiment, will eliminate as much bias as possible using certain tools. The first tool to help eliminate bias in controlled experiments is to use a randomized controlled trial. In a randomized controlled trial, participants are randomly assigned to the treatment or control group and their assignment isn't based on anything other than chance. Random assignment like this helps ensure that the groups are comparable. The second way is to use a placebo, which is something that resembles the treatment, but has no effect. This way, participants don't know if they're in the treatment or control group. This ensures that the effect of the treatment is due to the treatment itself, not the idea of getting the treatment. This is common in clinical trials that test the effectiveness of a drug. The control group will still be given a pill, but it's a sugar pill that has minimal effects on the response.\n\n**5. The gold standard of experiments will use...**\n\nIn a double-blind experiment, the person administering the treatment or running the experiment also doesn't know whether they're administering the actual treatment or the placebo. This protects against bias in the response as well as the analysis of the results. These different tools all boil down to the same principle: if there are fewer opportunities for bias to creep into your experiment, the more reliably you can conclude whether the treatment affects the response.\n\n**6. Observational studies**\n\nThe other kind of study we'll discuss is the observational study. In an observational study, participants are not randomly assigned to groups. Instead, participants assign themselves, usually based on pre-existing characteristics. This is useful for answering questions that aren't conducive to a controlled experiment. If you want to study the effect of smoking on cancer, you can't force people to start smoking. Similarly, if you want to study how past purchasing behavior affects whether someone will buy a product, you can't force people to have certain past purchasing behavior. Because assignment isn't random, there's no way to guarantee that the groups will be comparable in every aspect, so observational studies can't establish causation, only association. The effects of the treatment may be confounded by factors that got certain people into the control group and certain people into the treatment group. However, there are ways to control for confounders, which can help strengthen the reliability of conclusions about association.\n\n**7. Longitudinal vs. cross-sectional studies**\n\nThe final important distinction to make is between longitudinal and cross-sectional studies. In a longitudinal study, the same participants are followed over a period of time to examine the effect of treatment on the response. In a cross-sectional study, data is collected from a single snapshot in time. If you wanted to investigate the effect of age on height, a cross-sectional study would measure the heights of people of different ages and compare them. However, the results will be confounded by birth year and lifestyle since it's possible that each generation is getting taller. In a longitudinal study,the same people would have their heights recorded at different points in their lives, so the confounding is eliminated. It's important to note that longitudinal studies are more expensive, and take longer to perform, while cross-sectional studies are cheaper, faster, and more convenient.\n\n**8. Let's practice!**\n\nTime to practice your study design skills! \n\n## Study types\n\nWhile controlled experiments are ideal, many situations and research questions are not conducive to a controlled experiment. In a controlled experiment, causation can likely be inferred if the control and test groups have similar characteristics and don't have any systematic difference between them. On the other hand, causation cannot usually be inferred from observational studies, whose results are often misinterpreted as a result.\n\nIn this exercise, you'll practice distinguishing controlled experiments from observational studies.\n\nDetermine if each study is a controlled experiment or observational study.\n\n| Controlled Experiment | Observational Study | \n| --- | --- |\n| Purchasing rates are compared between users of an e-commerce site who are randomly directed to a new version of the home page or an old version. | A week ago, the home page of an e-commerce site was updated. Purchasing rates are compared between users who saw the old and new home page versions. |\n| Subjects are randomly assigned to a diet and weight loss is compared. | Prevalence of heart disease is compared between veterans with PTSD and veterans without PTSD. |\n| Asthma symptoms are compared between children randomly assigned to receive professional home pest management services or pest management education. | |\n\n## Longitudinal vs. cross-sectional studies\n\n<div class=\"\">A company manufactures thermometers, and they want to study the relationship between a thermometer's age and its accuracy. To do this, they take a sample of 100 different thermometers of different ages and test how accurate they are. Is this data longitudinal or cross-sectional?\n\n> *Question*\n> ---\n> Which of the following could be a *confounder* in this study?<br>\n> <br>\n> ⬜  Longitudinal<br>\n> ✅  Cross-sectional<br>\n> ⬜  Both<br>\n> ⬜  Neither<br>\n\nPerfect! This is a cross-sectional study since researchers aren't following the same set of thermometers over time and repeatedly measuring their accuracy at different ages.\n\n## Congratulations!\n\nTheory. Coming soon ...\n\n\n**1. Congratulations!**\n\nCongratulations on completing the course! You now have foundational statistics skills that you can use in your analyses and build upon further.\n\n**2. Overview**\n\nIn the first chapter of the course, you learned about what statistics can do, as well as summary statistics to measure the center and spread of a distribution.In the second chapter, you learned how to measure chance and how to use and interpret probability distributions. You also learned about the binomial distribution.In chapter three, you learned about the normal distribution and the central limit theorem, one of the most important ideas in statistics. You also saw how the Poisson distribution can be used to model countable outcomes.In the final chapter, you saw how to quantify relationships between two variables using correlation. You also learned about controlled experiments and observational studies and the conclusions that can and cannot be drawn from them.\n\n**3. Build on your skills**\n\nThere's still much more that you can do with statistics and much more to learn. Your new skills will set you up for success in this course on the foundations of regression.\n\n**4. Congratulations!**\n\nThanks for accompanying me on this statistical journey. Congratulations again!",
    "supporting": [
      "01_statistics_beginner_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}